
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



ANNOUNCE = '/ray/gui/server/announce'
COPYING = '/ray/gui/server/copying'
DISANNOUNCE = '/ray/gui/server/disannounce'
MESSAGE = '/ray/gui/server/message'
NSM_LOCKED = '/ray/gui/server/nsm_locked'
OPTIONS = '/ray/gui/server/options'
PARRALLEL_COPY_PROGRESS = '/ray/gui/server/parrallel_copy_progress'
PARRALLEL_COPY_STATE = '/ray/gui/server/parrallel_copy_state'
PROGRESS = '/ray/gui/server/progress'
RECENT_SESSIONS = '/ray/gui/server/recent_sessions'
ROOT = '/ray/gui/server/root'
STATUS = '/ray/gui/server/status'
TERMINAL_COMMAND = '/ray/gui/server/terminal_command'
AUTO_EXPORT_CUSTOM_NAMES = '/ray/gui/server/auto_export_custom_names'
'informs the GUI that "auto export custom names" option has changed (arg types: i)'
