# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/add_application.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogAddApplication(object):
    def setupUi(self, DialogAddApplication):
        DialogAddApplication.setObjectName("DialogAddApplication")
        DialogAddApplication.setWindowModality(QtCore.Qt.NonModal)
        DialogAddApplication.resize(731, 533)
        DialogAddApplication.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogAddApplication)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(DialogAddApplication)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.filterBar = OpenSessionFilterBar(self.groupBox)
        self.filterBar.setObjectName("filterBar")
        self.horizontalLayout_2.addWidget(self.filterBar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.groupBox)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 0, 3, 2, 1)
        self.checkBoxFactory = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxFactory.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxFactory.setChecked(True)
        self.checkBoxFactory.setObjectName("checkBoxFactory")
        self.gridLayout.addWidget(self.checkBoxFactory, 0, 2, 1, 1)
        self.checkBoxNsm = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxNsm.setChecked(True)
        self.checkBoxNsm.setObjectName("checkBoxNsm")
        self.gridLayout.addWidget(self.checkBoxNsm, 0, 4, 1, 1)
        self.checkBoxUser = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxUser.setChecked(True)
        self.checkBoxUser.setObjectName("checkBoxUser")
        self.gridLayout.addWidget(self.checkBoxUser, 1, 2, 1, 1)
        self.checkBoxRayHack = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxRayHack.setCheckable(True)
        self.checkBoxRayHack.setChecked(True)
        self.checkBoxRayHack.setObjectName("checkBoxRayHack")
        self.gridLayout.addWidget(self.checkBoxRayHack, 1, 4, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 0, 1, 2, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(DialogAddApplication)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widgetTemplateInfos = QtWidgets.QWidget(self.groupBox_2)
        self.widgetTemplateInfos.setStyleSheet("")
        self.widgetTemplateInfos.setObjectName("widgetTemplateInfos")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widgetTemplateInfos)
        self.verticalLayout_6.setContentsMargins(6, -1, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButtonIcon = FakeToolButton(self.widgetTemplateInfos)
        self.toolButtonIcon.setStyleSheet("QToolButton{border:none}")
        icon = QtGui.QIcon.fromTheme("application-pdf")
        self.toolButtonIcon.setIcon(icon)
        self.toolButtonIcon.setIconSize(QtCore.QSize(64, 64))
        self.toolButtonIcon.setObjectName("toolButtonIcon")
        self.horizontalLayout_4.addWidget(self.toolButtonIcon)
        self.labelTemplateName = QtWidgets.QLabel(self.widgetTemplateInfos)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTemplateName.setFont(font)
        self.labelTemplateName.setObjectName("labelTemplateName")
        self.horizontalLayout_4.addWidget(self.labelTemplateName)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toolButtonUser = QtWidgets.QToolButton(self.widgetTemplateInfos)
        self.toolButtonUser.setStyleSheet("QToolButton::menu-indicator{ image: url(none.jpg);}\\nQToolButton {border: none}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/scalable/breeze/im-user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonUser.setIcon(icon)
        self.toolButtonUser.setIconSize(QtCore.QSize(22, 22))
        self.toolButtonUser.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolButtonUser.setObjectName("toolButtonUser")
        self.horizontalLayout_5.addWidget(self.toolButtonUser)
        self.toolButtonFavorite = favoriteToolButton(self.widgetTemplateInfos)
        self.toolButtonFavorite.setStyleSheet("QToolButton {border: none}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/scalable/breeze/draw-star.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonFavorite.setIcon(icon1)
        self.toolButtonFavorite.setIconSize(QtCore.QSize(22, 22))
        self.toolButtonFavorite.setObjectName("toolButtonFavorite")
        self.horizontalLayout_5.addWidget(self.toolButtonFavorite)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.labelDescription = QtWidgets.QLabel(self.widgetTemplateInfos)
        font = QtGui.QFont()
        font.setItalic(True)
        self.labelDescription.setFont(font)
        self.labelDescription.setWordWrap(True)
        self.labelDescription.setObjectName("labelDescription")
        self.verticalLayout_6.addWidget(self.labelDescription)
        self.line = QtWidgets.QFrame(self.widgetTemplateInfos)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.widgetNonSaveable = QtWidgets.QWidget(self.widgetTemplateInfos)
        self.widgetNonSaveable.setObjectName("widgetNonSaveable")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widgetNonSaveable)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.line_3 = QtWidgets.QFrame(self.widgetNonSaveable)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_7.addWidget(self.line_3)
        self.toolButtonNoSave = FakeToolButton(self.widgetNonSaveable)
        self.toolButtonNoSave.setStyleSheet("QToolButton{border:none}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/scalable/breeze/document-nosave.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonNoSave.setIcon(icon2)
        self.toolButtonNoSave.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonNoSave.setObjectName("toolButtonNoSave")
        self.horizontalLayout_7.addWidget(self.toolButtonNoSave)
        self.label_2 = QtWidgets.QLabel(self.widgetNonSaveable)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{color:#f19d02}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.line_2 = QtWidgets.QFrame(self.widgetNonSaveable)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_7.addWidget(self.line_2)
        self.verticalLayout_6.addWidget(self.widgetNonSaveable)
        self.gridLayoutInfos = QtWidgets.QGridLayout()
        self.gridLayoutInfos.setObjectName("gridLayoutInfos")
        self.labelProtocolColon = QtWidgets.QLabel(self.widgetTemplateInfos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelProtocolColon.sizePolicy().hasHeightForWidth())
        self.labelProtocolColon.setSizePolicy(sizePolicy)
        self.labelProtocolColon.setObjectName("labelProtocolColon")
        self.gridLayoutInfos.addWidget(self.labelProtocolColon, 3, 1, 1, 1)
        self.labelProtocolTitle = QtWidgets.QLabel(self.widgetTemplateInfos)
        self.labelProtocolTitle.setObjectName("labelProtocolTitle")
        self.gridLayoutInfos.addWidget(self.labelProtocolTitle, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widgetTemplateInfos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayoutInfos.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widgetTemplateInfos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayoutInfos.addWidget(self.label_12, 4, 1, 1, 1)
        self.labelLabel = QtWidgets.QLabel(self.widgetTemplateInfos)
        self.labelLabel.setObjectName("labelLabel")
        self.gridLayoutInfos.addWidget(self.labelLabel, 5, 2, 1, 2)
        self.labelLabelTitle = QtWidgets.QLabel(self.widgetTemplateInfos)
        self.labelLabelTitle.setObjectName("labelLabelTitle")
        self.gridLayoutInfos.addWidget(self.labelLabelTitle, 5, 0, 1, 1)
        self.labelLabelColon = QtWidgets.QLabel(self.widgetTemplateInfos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLabelColon.sizePolicy().hasHeightForWidth())
        self.labelLabelColon.setSizePolicy(sizePolicy)
        self.labelLabelColon.setObjectName("labelLabelColon")
        self.gridLayoutInfos.addWidget(self.labelLabelColon, 5, 1, 1, 1)
        self.labelExecutable = QtWidgets.QLabel(self.widgetTemplateInfos)
        self.labelExecutable.setObjectName("labelExecutable")
        self.gridLayoutInfos.addWidget(self.labelExecutable, 4, 2, 1, 2)
        self.labelProtocol = QtWidgets.QLabel(self.widgetTemplateInfos)
        self.labelProtocol.setObjectName("labelProtocol")
        self.gridLayoutInfos.addWidget(self.labelProtocol, 3, 2, 1, 2)
        self.labelNameTitle = QtWidgets.QLabel(self.widgetTemplateInfos)
        self.labelNameTitle.setObjectName("labelNameTitle")
        self.gridLayoutInfos.addWidget(self.labelNameTitle, 6, 0, 1, 1)
        self.labelNameColon = QtWidgets.QLabel(self.widgetTemplateInfos)
        self.labelNameColon.setObjectName("labelNameColon")
        self.gridLayoutInfos.addWidget(self.labelNameColon, 6, 1, 1, 1)
        self.labelName = QtWidgets.QLabel(self.widgetTemplateInfos)
        self.labelName.setObjectName("labelName")
        self.gridLayoutInfos.addWidget(self.labelName, 6, 2, 1, 2)
        self.verticalLayout_6.addLayout(self.gridLayoutInfos)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.toolButtonAdvanced = QtWidgets.QToolButton(self.widgetTemplateInfos)
        icon = QtGui.QIcon.fromTheme("dialog-information")
        self.toolButtonAdvanced.setIcon(icon)
        self.toolButtonAdvanced.setObjectName("toolButtonAdvanced")
        self.horizontalLayout_6.addWidget(self.toolButtonAdvanced)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addWidget(self.widgetTemplateInfos)
        self.widgetNoTemplate = QtWidgets.QWidget(self.groupBox_2)
        self.widgetNoTemplate.setStyleSheet("")
        self.widgetNoTemplate.setObjectName("widgetNoTemplate")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widgetNoTemplate)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem5)
        self.labelNoTemplate = QtWidgets.QLabel(self.widgetNoTemplate)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.labelNoTemplate.setFont(font)
        self.labelNoTemplate.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNoTemplate.setObjectName("labelNoTemplate")
        self.verticalLayout_7.addWidget(self.labelNoTemplate)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)
        self.verticalLayout_4.addWidget(self.widgetNoTemplate)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.templateList = QtWidgets.QListWidget(DialogAddApplication)
        self.templateList.setAlternatingRowColors(False)
        self.templateList.setObjectName("templateList")
        self.horizontalLayout_3.addWidget(self.templateList)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogAddApplication)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogAddApplication)
        self.buttonBox.accepted.connect(DialogAddApplication.accept)
        self.buttonBox.rejected.connect(DialogAddApplication.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogAddApplication)

    def retranslateUi(self, DialogAddApplication):
        _translate = QtCore.QCoreApplication.translate
        DialogAddApplication.setWindowTitle(_translate("DialogAddApplication", "Add Application"))
        self.label.setText(_translate("DialogAddApplication", "Filter :"))
        self.checkBoxFactory.setText(_translate("DialogAddApplication", "Factory"))
        self.checkBoxNsm.setToolTip(_translate("DialogAddApplication", "<html><head/><body><p>NSM is the protocol used by modern audio programs to ensure a good session management.</p></body></html>"))
        self.checkBoxNsm.setText(_translate("DialogAddApplication", "NSM"))
        self.checkBoxUser.setText(_translate("DialogAddApplication", "User"))
        self.checkBoxRayHack.setToolTip(_translate("DialogAddApplication", "<html><head/><body><p><span style=\" font-weight:600;\">Ray-Hack</span> is a fake protocol that tries to manage non NSM compatible programs as it can.</p><p>It can be useful :</p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">for audio programs that don\'t have NSM implementation yet</li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">for non-audio programs</li></ul></body></html>"))
        self.checkBoxRayHack.setText(_translate("DialogAddApplication", "Ray-Hack"))
        self.toolButtonIcon.setText(_translate("DialogAddApplication", "..."))
        self.labelTemplateName.setText(_translate("DialogAddApplication", "MacronDemission"))
        self.toolButtonUser.setText(_translate("DialogAddApplication", "..."))
        self.toolButtonFavorite.setToolTip(_translate("DialogAddApplication", "<html><head/><body><p>Add this template to favorites / Remove this template from favorites</p></body></html>"))
        self.toolButtonFavorite.setText(_translate("DialogAddApplication", "..."))
        self.labelDescription.setText(_translate("DialogAddApplication", "resistance to the oppression of pests"))
        self.toolButtonNoSave.setText(_translate("DialogAddApplication", "..."))
        self.label_2.setText(_translate("DialogAddApplication", "Non Saveable Program !!!"))
        self.labelProtocolColon.setText(_translate("DialogAddApplication", ":"))
        self.labelProtocolTitle.setText(_translate("DialogAddApplication", "Protocol"))
        self.label_8.setText(_translate("DialogAddApplication", "Executable"))
        self.label_12.setText(_translate("DialogAddApplication", ":"))
        self.labelLabel.setText(_translate("DialogAddApplication", "label"))
        self.labelLabelTitle.setText(_translate("DialogAddApplication", "Label"))
        self.labelLabelColon.setText(_translate("DialogAddApplication", ":"))
        self.labelExecutable.setText(_translate("DialogAddApplication", "lallement"))
        self.labelProtocol.setText(_translate("DialogAddApplication", "NLP"))
        self.labelNameTitle.setText(_translate("DialogAddApplication", "Name"))
        self.labelNameColon.setText(_translate("DialogAddApplication", ":"))
        self.labelName.setText(_translate("DialogAddApplication", "Program Name"))
        self.toolButtonAdvanced.setToolTip(_translate("DialogAddApplication", "<html><head/><body><p>Get more informations on this template.</p></body></html>"))
        self.toolButtonAdvanced.setText(_translate("DialogAddApplication", "..."))
        self.labelNoTemplate.setText(_translate("DialogAddApplication", "No template selected"))
        self.templateList.setSortingEnabled(True)

from surclassed_widgets import FakeToolButton, OpenSessionFilterBar, favoriteToolButton
import resources_rc
