# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/client_slot_2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ClientSlotWidget(object):
    def setupUi(self, ClientSlotWidget):
        ClientSlotWidget.setObjectName("ClientSlotWidget")
        ClientSlotWidget.resize(514, 199)
        ClientSlotWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.verticalLayout = QtWidgets.QVBoxLayout(ClientSlotWidget)
        self.verticalLayout.setContentsMargins(0, 3, 0, 3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setSpacing(2)
        self.mainLayout.setObjectName("mainLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.iconButton = QtWidgets.QToolButton(ClientSlotWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconButton.sizePolicy().hasHeightForWidth())
        self.iconButton.setSizePolicy(sizePolicy)
        self.iconButton.setMinimumSize(QtCore.QSize(32, 32))
        self.iconButton.setMaximumSize(QtCore.QSize(32, 32))
        self.iconButton.setStyleSheet("QToolButton::menu-indicator{ image: url(none.jpg);}\n"
"QToolButton {border: none}")
        self.iconButton.setIconSize(QtCore.QSize(32, 32))
        self.iconButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.iconButton.setObjectName("iconButton")
        self.horizontalLayout_2.addWidget(self.iconButton)
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line = QtWidgets.QFrame(ClientSlotWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.ClientName = QtWidgets.QLabel(ClientSlotWidget)
        self.ClientName.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClientName.sizePolicy().hasHeightForWidth())
        self.ClientName.setSizePolicy(sizePolicy)
        self.ClientName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ClientName.setStyleSheet("font-weight : bold")
        self.ClientName.setObjectName("ClientName")
        self.verticalLayout_4.addWidget(self.ClientName)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.mainLayout.addLayout(self.horizontalLayout_2)
        self.layout_top = QtWidgets.QHBoxLayout()
        self.layout_top.setSpacing(0)
        self.layout_top.setObjectName("layout_top")
        self.spacerLeftOfDown = QtWidgets.QWidget(ClientSlotWidget)
        self.spacerLeftOfDown.setObjectName("spacerLeftOfDown")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.spacerLeftOfDown)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.layout_top.addWidget(self.spacerLeftOfDown)
        self.toolButtonHack = RayHackButton(ClientSlotWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonHack.sizePolicy().hasHeightForWidth())
        self.toolButtonHack.setSizePolicy(sizePolicy)
        self.toolButtonHack.setMinimumSize(QtCore.QSize(36, 20))
        self.toolButtonHack.setMaximumSize(QtCore.QSize(36, 24))
        self.toolButtonHack.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/scalable/breeze/layer-visible-on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonHack.setIcon(icon)
        self.toolButtonHack.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonHack.setCheckable(True)
        self.toolButtonHack.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonHack.setObjectName("toolButtonHack")
        self.layout_top.addWidget(self.toolButtonHack)
        self.toolButtonGUI = QtWidgets.QToolButton(ClientSlotWidget)
        self.toolButtonGUI.setStyleSheet("QToolButton{border:none}")
        self.toolButtonGUI.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonGUI.setIcon(icon1)
        self.toolButtonGUI.setIconSize(QtCore.QSize(22, 22))
        self.toolButtonGUI.setObjectName("toolButtonGUI")
        self.layout_top.addWidget(self.toolButtonGUI)
        spacerItem7 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.layout_top.addItem(spacerItem7)
        self.startButton = QtWidgets.QToolButton(ClientSlotWidget)
        self.startButton.setMaximumSize(QtCore.QSize(32, 32))
        self.startButton.setStyleSheet("QToolButton {border: none}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/scalable/breeze/media-playback-start.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/scalable/breeze/disabled/media-playback-start.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.startButton.setIcon(icon2)
        self.startButton.setIconSize(QtCore.QSize(32, 32))
        self.startButton.setObjectName("startButton")
        self.layout_top.addWidget(self.startButton)
        self.stopButton = QtWidgets.QToolButton(ClientSlotWidget)
        self.stopButton.setEnabled(False)
        self.stopButton.setMaximumSize(QtCore.QSize(32, 32))
        self.stopButton.setStyleSheet("QToolButton {border: none}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/scalable/breeze/media-playback-stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/scalable/breeze/disabled/media-playback-stop.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon3)
        self.stopButton.setIconSize(QtCore.QSize(32, 32))
        self.stopButton.setObjectName("stopButton")
        self.layout_top.addWidget(self.stopButton)
        self.lineEditClientStatus = StatusBar(ClientSlotWidget)
        self.lineEditClientStatus.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditClientStatus.sizePolicy().hasHeightForWidth())
        self.lineEditClientStatus.setSizePolicy(sizePolicy)
        self.lineEditClientStatus.setMaximumSize(QtCore.QSize(60, 28))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEditClientStatus.setFont(font)
        self.lineEditClientStatus.setFrame(True)
        self.lineEditClientStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditClientStatus.setReadOnly(True)
        self.lineEditClientStatus.setObjectName("lineEditClientStatus")
        self.layout_top.addWidget(self.lineEditClientStatus)
        self.saveButton = QtWidgets.QToolButton(ClientSlotWidget)
        self.saveButton.setEnabled(False)
        self.saveButton.setMaximumSize(QtCore.QSize(32, 32))
        self.saveButton.setStyleSheet("QToolButton {border: none}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/scalable/breeze/document-save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/scalable/breeze/disabled/document-save.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon4)
        self.saveButton.setIconSize(QtCore.QSize(32, 32))
        self.saveButton.setObjectName("saveButton")
        self.layout_top.addWidget(self.saveButton)
        spacerItem8 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.layout_top.addItem(spacerItem8)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.closeButton = QtWidgets.QToolButton(ClientSlotWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setMaximumSize(QtCore.QSize(22, 22))
        self.closeButton.setStyleSheet("QToolButton {border: none}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/scalable/breeze/window-close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon5)
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout_2.addWidget(self.closeButton)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.layout_top.addLayout(self.verticalLayout_2)
        self.mainLayout.addLayout(self.layout_top)
        self.verticalLayout.addLayout(self.mainLayout)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.actionSaveAsApplicationTemplate = QtWidgets.QAction(ClientSlotWidget)
        icon = QtGui.QIcon.fromTheme("document-save-as-template")
        self.actionSaveAsApplicationTemplate.setIcon(icon)
        self.actionSaveAsApplicationTemplate.setObjectName("actionSaveAsApplicationTemplate")
        self.actionProperties = QtWidgets.QAction(ClientSlotWidget)
        icon = QtGui.QIcon.fromTheme("document-properties")
        self.actionProperties.setIcon(icon)
        self.actionProperties.setObjectName("actionProperties")
        self.actionReturnToAPreviousState = QtWidgets.QAction(ClientSlotWidget)
        icon = QtGui.QIcon.fromTheme("media-seek-backward")
        self.actionReturnToAPreviousState.setIcon(icon)
        self.actionReturnToAPreviousState.setObjectName("actionReturnToAPreviousState")
        self.actionRename = QtWidgets.QAction(ClientSlotWidget)
        icon = QtGui.QIcon.fromTheme("edit-rename")
        self.actionRename.setIcon(icon)
        self.actionRename.setObjectName("actionRename")

        self.retranslateUi(ClientSlotWidget)
        QtCore.QMetaObject.connectSlotsByName(ClientSlotWidget)

    def retranslateUi(self, ClientSlotWidget):
        _translate = QtCore.QCoreApplication.translate
        ClientSlotWidget.setWindowTitle(_translate("ClientSlotWidget", "Frame"))
        self.iconButton.setText(_translate("ClientSlotWidget", "..."))
        self.ClientName.setText(_translate("ClientSlotWidget", "ClientName"))
        self.toolButtonHack.setToolTip(_translate("ClientSlotWidget", "Display client Ray-Hack properties"))
        self.toolButtonHack.setText(_translate("ClientSlotWidget", "Hack"))
        self.startButton.setToolTip(_translate("ClientSlotWidget", "Launch"))
        self.startButton.setText(_translate("ClientSlotWidget", "..."))
        self.stopButton.setToolTip(_translate("ClientSlotWidget", "<html><head/><body><p>Politely ask the client to stop.</p></body></html>"))
        self.stopButton.setText(_translate("ClientSlotWidget", "..."))
        self.lineEditClientStatus.setToolTip(_translate("ClientSlotWidget", "Status"))
        self.lineEditClientStatus.setText(_translate("ClientSlotWidget", "stopped"))
        self.saveButton.setToolTip(_translate("ClientSlotWidget", "Save"))
        self.saveButton.setText(_translate("ClientSlotWidget", "..."))
        self.closeButton.setToolTip(_translate("ClientSlotWidget", "Remove"))
        self.closeButton.setText(_translate("ClientSlotWidget", "..."))
        self.actionSaveAsApplicationTemplate.setText(_translate("ClientSlotWidget", "Save As Application Template"))
        self.actionProperties.setText(_translate("ClientSlotWidget", "Properties"))
        self.actionReturnToAPreviousState.setText(_translate("ClientSlotWidget", "Return To A Previous State"))
        self.actionRename.setText(_translate("ClientSlotWidget", "Rename"))

from surclassed_widgets import RayHackButton, StatusBar
import resources_rc
