# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/patchbay_tools.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(848, 34)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labelSamplerateTitle = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelSamplerateTitle.setFont(font)
        self.labelSamplerateTitle.setObjectName("labelSamplerateTitle")
        self.horizontalLayout.addWidget(self.labelSamplerateTitle)
        self.labelSamplerate = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelSamplerate.setFont(font)
        self.labelSamplerate.setObjectName("labelSamplerate")
        self.horizontalLayout.addWidget(self.labelSamplerate)
        self.labelSamplerateUnits = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelSamplerateUnits.setFont(font)
        self.labelSamplerateUnits.setObjectName("labelSamplerateUnits")
        self.horizontalLayout.addWidget(self.labelSamplerateUnits)
        self.lineSep1 = QtWidgets.QFrame(Form)
        self.lineSep1.setFrameShape(QtWidgets.QFrame.VLine)
        self.lineSep1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineSep1.setObjectName("lineSep1")
        self.horizontalLayout.addWidget(self.lineSep1)
        self.labelBuffer = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelBuffer.setFont(font)
        self.labelBuffer.setObjectName("labelBuffer")
        self.horizontalLayout.addWidget(self.labelBuffer)
        self.comboBoxBuffer = QtWidgets.QComboBox(Form)
        self.comboBoxBuffer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBoxBuffer.setFont(font)
        self.comboBoxBuffer.setStyleSheet("QCombobox{align:right}")
        self.comboBoxBuffer.setObjectName("comboBoxBuffer")
        self.horizontalLayout.addWidget(self.comboBoxBuffer)
        self.lineSep2 = QtWidgets.QFrame(Form)
        self.lineSep2.setFrameShape(QtWidgets.QFrame.VLine)
        self.lineSep2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineSep2.setObjectName("lineSep2")
        self.horizontalLayout.addWidget(self.lineSep2)
        self.pushButtonXruns = QtWidgets.QPushButton(Form)
        self.pushButtonXruns.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButtonXruns.setFont(font)
        self.pushButtonXruns.setStyleSheet("QPushButton{border:none}")
        self.pushButtonXruns.setObjectName("pushButtonXruns")
        self.horizontalLayout.addWidget(self.pushButtonXruns)
        self.lineSep3 = QtWidgets.QFrame(Form)
        self.lineSep3.setFrameShape(QtWidgets.QFrame.VLine)
        self.lineSep3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineSep3.setObjectName("lineSep3")
        self.horizontalLayout.addWidget(self.lineSep3)
        self.labelDsp = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelDsp.setFont(font)
        self.labelDsp.setObjectName("labelDsp")
        self.horizontalLayout.addWidget(self.labelDsp)
        self.progressBarDsp = QtWidgets.QProgressBar(Form)
        self.progressBarDsp.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progressBarDsp.setFont(font)
        self.progressBarDsp.setProperty("value", 0)
        self.progressBarDsp.setObjectName("progressBarDsp")
        self.horizontalLayout.addWidget(self.progressBarDsp)
        self.labelJackNotStarted = QtWidgets.QLabel(Form)
        self.labelJackNotStarted.setObjectName("labelJackNotStarted")
        self.horizontalLayout.addWidget(self.labelJackNotStarted)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelSamplerateTitle.setText(_translate("Form", "Sample Rate :"))
        self.labelSamplerate.setText(_translate("Form", "48.000"))
        self.labelSamplerateUnits.setText(_translate("Form", "Hz"))
        self.labelBuffer.setText(_translate("Form", "Buffer :"))
        self.pushButtonXruns.setText(_translate("Form", "0 Xruns"))
        self.labelDsp.setText(_translate("Form", "DSP :"))
        self.labelJackNotStarted.setText(_translate("Form", "<p style=\"color:red\">JACK is not started !</p>"))

