
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



ADD_XRUN = '/ray/gui/patchbay/add_xrun'
ANNOUNCE = '/ray/gui/patchbay/announce'
BIG_PACKETS = '/ray/gui/patchbay/big_packets'
BUFFER_SIZE = '/ray/gui/patchbay/buffer_size'
CLIENT_NAME_AND_UUID = '/ray/gui/patchbay/client_name_and_uuid'
CONNECTION_ADDED = '/ray/gui/patchbay/connection_added'
CONNECTION_REMOVED = '/ray/gui/patchbay/connection_removed'
DSP_LOAD = '/ray/gui/patchbay/dsp_load'
METADATA_UPDATED = '/ray/gui/patchbay/metadata_updated'
PORT_ADDED = '/ray/gui/patchbay/port_added'
PORT_REMOVED = '/ray/gui/patchbay/port_removed'
PORT_RENAMED = '/ray/gui/patchbay/port_renamed'
SAMPLE_RATE = '/ray/gui/patchbay/sample_rate'
SERVER_LOSE = '/ray/gui/patchbay/server_lose'
SERVER_STARTED = '/ray/gui/patchbay/server_started'
SERVER_STOPPED = '/ray/gui/patchbay/server_stopped'
TRANSPORT_POSITION = '/ray/gui/patchbay/transport_position'
UPDATE_GROUP_POSITION = '/ray/gui/patchbay/update_group_position'
UPDATE_GROUP_PRETTY_NAME = '/ray/gui/patchbay/update_group_pretty_name'
UPDATE_PORT_PRETTY_NAME = '/ray/gui/patchbay/update_port_pretty_name'
UPDATE_PORTGROUP = '/ray/gui/patchbay/update_portgroup'
VIEWS_CHANGED = '/ray/gui/patchbay/views_changed'