
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



DETAILS = '/ray/gui/listed_session/details'
SCRIPTED_DIR = '/ray/gui/listed_session/scripted_dir'
' (arg types: si)'
