
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



ABORT = '/nsm/server/abort'
ADD = '/nsm/server/add'
ANNOUNCE = '/nsm/server/announce'
BROADCAST = '/nsm/server/broadcast'
CLOSE = '/nsm/server/close'
DUPLICATE = '/nsm/server/duplicate'
LIST = '/nsm/server/list'
MONITOR_RESET = '/nsm/server/monitor_reset'
NEW = '/nsm/server/new'
OPEN = '/nsm/server/open'
QUIT = '/nsm/server/quit'
SAVE = '/nsm/server/save'