# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/client_slot.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ClientSlotWidget(object):
    def setupUi(self, ClientSlotWidget):
        ClientSlotWidget.setObjectName("ClientSlotWidget")
        ClientSlotWidget.resize(514, 133)
        ClientSlotWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.verticalLayout = QtWidgets.QVBoxLayout(ClientSlotWidget)
        self.verticalLayout.setContentsMargins(0, 3, 0, 3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_top = QtWidgets.QHBoxLayout()
        self.layout_top.setSpacing(0)
        self.layout_top.setObjectName("layout_top")
        spacerItem = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.layout_top.addItem(spacerItem)
        self.iconButton = QtWidgets.QToolButton(ClientSlotWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconButton.sizePolicy().hasHeightForWidth())
        self.iconButton.setSizePolicy(sizePolicy)
        self.iconButton.setMinimumSize(QtCore.QSize(32, 32))
        self.iconButton.setMaximumSize(QtCore.QSize(32, 32))
        self.iconButton.setStyleSheet("QToolButton::menu-indicator{ image: url(none.jpg);}\n"
"QToolButton {border: none}")
        self.iconButton.setIconSize(QtCore.QSize(32, 32))
        self.iconButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.iconButton.setObjectName("iconButton")
        self.layout_top.addWidget(self.iconButton)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.layout_top.addItem(spacerItem1)
        self.ClientName = QtWidgets.QLabel(ClientSlotWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClientName.sizePolicy().hasHeightForWidth())
        self.ClientName.setSizePolicy(sizePolicy)
        self.ClientName.setStyleSheet("font-weight : bold")
        self.ClientName.setObjectName("ClientName")
        self.layout_top.addWidget(self.ClientName)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_top.addItem(spacerItem2)
        self.toolButtonGUI = HideGuiButton(ClientSlotWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonGUI.sizePolicy().hasHeightForWidth())
        self.toolButtonGUI.setSizePolicy(sizePolicy)
        self.toolButtonGUI.setMinimumSize(QtCore.QSize(36, 20))
        self.toolButtonGUI.setMaximumSize(QtCore.QSize(36, 24))
        self.toolButtonGUI.setAutoFillBackground(False)
        icon = QtGui.QIcon.fromTheme("interface")
        self.toolButtonGUI.setIcon(icon)
        self.toolButtonGUI.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonGUI.setCheckable(True)
        self.toolButtonGUI.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonGUI.setObjectName("toolButtonGUI")
        self.layout_top.addWidget(self.toolButtonGUI)
        spacerItem3 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.layout_top.addItem(spacerItem3)
        self.startButton = QtWidgets.QToolButton(ClientSlotWidget)
        self.startButton.setMaximumSize(QtCore.QSize(32, 32))
        self.startButton.setStyleSheet("QToolButton {border: none}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/scalable/breeze/media-playback-start.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/scalable/breeze/disabled/media-playback-start.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.startButton.setIcon(icon)
        self.startButton.setIconSize(QtCore.QSize(32, 32))
        self.startButton.setObjectName("startButton")
        self.layout_top.addWidget(self.startButton)
        self.stopButton = QtWidgets.QToolButton(ClientSlotWidget)
        self.stopButton.setEnabled(False)
        self.stopButton.setMaximumSize(QtCore.QSize(32, 32))
        self.stopButton.setStyleSheet("QToolButton {border: none}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/scalable/breeze/media-playback-stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/scalable/breeze/disabled/media-playback-stop.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon1)
        self.stopButton.setIconSize(QtCore.QSize(32, 32))
        self.stopButton.setObjectName("stopButton")
        self.layout_top.addWidget(self.stopButton)
        self.killButton = QtWidgets.QToolButton(ClientSlotWidget)
        self.killButton.setEnabled(True)
        self.killButton.setMaximumSize(QtCore.QSize(32, 32))
        self.killButton.setStyleSheet("QToolButton {border: none}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/scalable/breeze/media-playback-stop-red.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.killButton.setIcon(icon2)
        self.killButton.setIconSize(QtCore.QSize(32, 32))
        self.killButton.setObjectName("killButton")
        self.layout_top.addWidget(self.killButton)
        self.lineEditClientStatus = StatusBar(ClientSlotWidget)
        self.lineEditClientStatus.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditClientStatus.sizePolicy().hasHeightForWidth())
        self.lineEditClientStatus.setSizePolicy(sizePolicy)
        self.lineEditClientStatus.setMaximumSize(QtCore.QSize(60, 28))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEditClientStatus.setFont(font)
        self.lineEditClientStatus.setFrame(True)
        self.lineEditClientStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditClientStatus.setReadOnly(True)
        self.lineEditClientStatus.setObjectName("lineEditClientStatus")
        self.layout_top.addWidget(self.lineEditClientStatus)
        self.saveButton = QtWidgets.QToolButton(ClientSlotWidget)
        self.saveButton.setEnabled(False)
        self.saveButton.setMaximumSize(QtCore.QSize(32, 32))
        self.saveButton.setStyleSheet("QToolButton {border: none}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/scalable/breeze/document-save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/scalable/breeze/disabled/document-save.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon3)
        self.saveButton.setIconSize(QtCore.QSize(32, 32))
        self.saveButton.setObjectName("saveButton")
        self.layout_top.addWidget(self.saveButton)
        spacerItem4 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.layout_top.addItem(spacerItem4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.closeButton = QtWidgets.QToolButton(ClientSlotWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setMaximumSize(QtCore.QSize(22, 22))
        self.closeButton.setStyleSheet("QToolButton {border: none}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/scalable/breeze/window-close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon4)
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout_2.addWidget(self.closeButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.layout_top.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.layout_top)
        self.actionSaveAsApplicationTemplate = QtWidgets.QAction(ClientSlotWidget)
        icon = QtGui.QIcon.fromTheme("document-save-as-template")
        self.actionSaveAsApplicationTemplate.setIcon(icon)
        self.actionSaveAsApplicationTemplate.setObjectName("actionSaveAsApplicationTemplate")
        self.actionProperties = QtWidgets.QAction(ClientSlotWidget)
        icon = QtGui.QIcon.fromTheme("document-properties")
        self.actionProperties.setIcon(icon)
        self.actionProperties.setObjectName("actionProperties")

        self.retranslateUi(ClientSlotWidget)
        QtCore.QMetaObject.connectSlotsByName(ClientSlotWidget)

    def retranslateUi(self, ClientSlotWidget):
        _translate = QtCore.QCoreApplication.translate
        ClientSlotWidget.setWindowTitle(_translate("ClientSlotWidget", "Frame"))
        self.iconButton.setText(_translate("ClientSlotWidget", "..."))
        self.ClientName.setText(_translate("ClientSlotWidget", "ClientName"))
        self.toolButtonGUI.setToolTip(_translate("ClientSlotWidget", "Show GUI"))
        self.toolButtonGUI.setText(_translate("ClientSlotWidget", "GUI"))
        self.startButton.setToolTip(_translate("ClientSlotWidget", "Launch"))
        self.startButton.setText(_translate("ClientSlotWidget", "..."))
        self.stopButton.setToolTip(_translate("ClientSlotWidget", "<html><head/><body><p>Politely ask the client to stop.</p></body></html>"))
        self.stopButton.setText(_translate("ClientSlotWidget", "..."))
        self.killButton.setToolTip(_translate("ClientSlotWidget", "<html><head/><body><p>Kill !</p></body></html>"))
        self.killButton.setText(_translate("ClientSlotWidget", "..."))
        self.lineEditClientStatus.setToolTip(_translate("ClientSlotWidget", "Status"))
        self.lineEditClientStatus.setText(_translate("ClientSlotWidget", "stopped"))
        self.saveButton.setToolTip(_translate("ClientSlotWidget", "Save"))
        self.saveButton.setText(_translate("ClientSlotWidget", "..."))
        self.closeButton.setToolTip(_translate("ClientSlotWidget", "Remove"))
        self.closeButton.setText(_translate("ClientSlotWidget", "..."))
        self.actionSaveAsApplicationTemplate.setText(_translate("ClientSlotWidget", "Save As Application Template"))
        self.actionProperties.setText(_translate("ClientSlotWidget", "Properties"))

from hide_gui_button import HideGuiButton
from status_bar import StatusBar
import resources_rc
