# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/client_trash.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(343, 329)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.labelClientName = QtWidgets.QLabel(Dialog)
        self.labelClientName.setObjectName("labelClientName")
        self.gridLayout.addWidget(self.labelClientName, 4, 2, 1, 2)
        self.label_8 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 1, 1, 1)
        self.labelExecutable = QtWidgets.QLabel(Dialog)
        self.labelExecutable.setObjectName("labelExecutable")
        self.gridLayout.addWidget(self.labelExecutable, 2, 2, 1, 2)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.toolButtonIcon = QtWidgets.QToolButton(Dialog)
        self.toolButtonIcon.setStyleSheet("QToolButton{border:none}")
        icon = QtGui.QIcon.fromTheme("application-pdf")
        self.toolButtonIcon.setIcon(icon)
        self.toolButtonIcon.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonIcon.setObjectName("toolButtonIcon")
        self.gridLayout.addWidget(self.toolButtonIcon, 2, 4, 3, 1)
        self.labelId = QtWidgets.QLabel(Dialog)
        self.labelId.setObjectName("labelId")
        self.gridLayout.addWidget(self.labelId, 3, 2, 1, 2)
        self.label_9 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.checkBoxSaveStop = QtWidgets.QCheckBox(Dialog)
        self.checkBoxSaveStop.setEnabled(False)
        self.checkBoxSaveStop.setChecked(True)
        self.checkBoxSaveStop.setObjectName("checkBoxSaveStop")
        self.gridLayout.addWidget(self.checkBoxSaveStop, 7, 0, 1, 5)
        self.labelClientLabel = QtWidgets.QLabel(Dialog)
        self.labelClientLabel.setObjectName("labelClientLabel")
        self.gridLayout.addWidget(self.labelClientLabel, 5, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 1)
        self.labelClientIcon = QtWidgets.QLabel(Dialog)
        self.labelClientIcon.setObjectName("labelClientIcon")
        self.gridLayout.addWidget(self.labelClientIcon, 6, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 6)
        self.pushButtonRemove = QtWidgets.QPushButton(Dialog)
        icon = QtGui.QIcon.fromTheme("draw-eraser-delete-objects")
        self.pushButtonRemove.setIcon(icon)
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.gridLayout.addWidget(self.pushButtonRemove, 9, 0, 1, 2)
        self.pushButtonCancel = QtWidgets.QPushButton(Dialog)
        icon = QtGui.QIcon.fromTheme("dialog-cancel")
        self.pushButtonCancel.setIcon(icon)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout.addWidget(self.pushButtonCancel, 9, 4, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.pushButtonRestore = QtWidgets.QPushButton(Dialog)
        icon = QtGui.QIcon.fromTheme("restoration")
        self.pushButtonRestore.setIcon(icon)
        self.pushButtonRestore.setObjectName("pushButtonRestore")
        self.gridLayout.addWidget(self.pushButtonRestore, 9, 2, 1, 2)

        self.retranslateUi(Dialog)
        self.pushButtonCancel.clicked.connect(Dialog.reject)
        self.pushButtonRestore.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Restore Client ?"))
        self.labelClientName.setText(_translate("Dialog", "client_name"))
        self.label_8.setText(_translate("Dialog", ":"))
        self.labelExecutable.setText(_translate("Dialog", "executable"))
        self.label_6.setText(_translate("Dialog", "Label"))
        self.label_5.setText(_translate("Dialog", "Icon"))
        self.toolButtonIcon.setText(_translate("Dialog", "..."))
        self.labelId.setText(_translate("Dialog", "nsmid"))
        self.label_9.setText(_translate("Dialog", ":"))
        self.label_4.setText(_translate("Dialog", ":"))
        self.label.setText(_translate("Dialog", "Executable"))
        self.label_10.setText(_translate("Dialog", ":"))
        self.label_2.setText(_translate("Dialog", "Name"))
        self.label_7.setText(_translate("Dialog", ":"))
        self.label_3.setText(_translate("Dialog", "Client id"))
        self.checkBoxSaveStop.setText(_translate("Dialog", "Prevent to stop without recent save"))
        self.labelClientLabel.setText(_translate("Dialog", "client_label"))
        self.labelClientIcon.setText(_translate("Dialog", "client_icon"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Do you want to restore this client in the session ?<br/>You can also definitely remove the client and its files.</p></body></html>"))
        self.pushButtonRemove.setToolTip(_translate("Dialog", "<html><head/><body><p>Remove definitely the client and its files.</p></body></html>"))
        self.pushButtonRemove.setText(_translate("Dialog", "Remove"))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancel"))
        self.pushButtonRestore.setToolTip(_translate("Dialog", "<html><head/><body><p>Restore this client in current session.</p></body></html>"))
        self.pushButtonRestore.setText(_translate("Dialog", "Restore Client"))

