# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/new_session.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogNewSession(object):
    def setupUi(self, DialogNewSession):
        DialogNewSession.setObjectName("DialogNewSession")
        DialogNewSession.setWindowModality(QtCore.Qt.NonModal)
        DialogNewSession.resize(228, 207)
        DialogNewSession.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogNewSession)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelSessionsFolder = QtWidgets.QLabel(DialogNewSession)
        self.labelSessionsFolder.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSessionsFolder.setObjectName("labelSessionsFolder")
        self.verticalLayout_2.addWidget(self.labelSessionsFolder)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.currentSessionsFolder = QtWidgets.QLabel(DialogNewSession)
        self.currentSessionsFolder.setStyleSheet("font-style :  italic")
        self.currentSessionsFolder.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentSessionsFolder.setObjectName("currentSessionsFolder")
        self.horizontalLayout_4.addWidget(self.currentSessionsFolder)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.toolButtonFolder = QtWidgets.QToolButton(DialogNewSession)
        icon = QtGui.QIcon.fromTheme("folder-open")
        self.toolButtonFolder.setIcon(icon)
        self.toolButtonFolder.setObjectName("toolButtonFolder")
        self.horizontalLayout_3.addWidget(self.toolButtonFolder)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.labelNewSessionName = QtWidgets.QLabel(DialogNewSession)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelNewSessionName.sizePolicy().hasHeightForWidth())
        self.labelNewSessionName.setSizePolicy(sizePolicy)
        self.labelNewSessionName.setObjectName("labelNewSessionName")
        self.verticalLayout.addWidget(self.labelNewSessionName)
        self.lineEdit = QtWidgets.QLineEdit(DialogNewSession)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayoutTemplate = QtWidgets.QHBoxLayout()
        self.horizontalLayoutTemplate.setObjectName("horizontalLayoutTemplate")
        self.labelTemplate = QtWidgets.QLabel(DialogNewSession)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTemplate.sizePolicy().hasHeightForWidth())
        self.labelTemplate.setSizePolicy(sizePolicy)
        self.labelTemplate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTemplate.setObjectName("labelTemplate")
        self.horizontalLayoutTemplate.addWidget(self.labelTemplate)
        self.comboBoxTemplate = QtWidgets.QComboBox(DialogNewSession)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxTemplate.sizePolicy().hasHeightForWidth())
        self.comboBoxTemplate.setSizePolicy(sizePolicy)
        self.comboBoxTemplate.setObjectName("comboBoxTemplate")
        self.horizontalLayoutTemplate.addWidget(self.comboBoxTemplate)
        self.verticalLayout.addLayout(self.horizontalLayoutTemplate)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogNewSession)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogNewSession)
        self.buttonBox.accepted.connect(DialogNewSession.accept)
        self.buttonBox.rejected.connect(DialogNewSession.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogNewSession)

    def retranslateUi(self, DialogNewSession):
        _translate = QtCore.QCoreApplication.translate
        DialogNewSession.setWindowTitle(_translate("DialogNewSession", "New Session"))
        self.labelSessionsFolder.setText(_translate("DialogNewSession", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Sessions Folder :</span></p></body></html>"))
        self.currentSessionsFolder.setText(_translate("DialogNewSession", "/home/user/Ray Sessions"))
        self.toolButtonFolder.setText(_translate("DialogNewSession", "Folder"))
        self.labelNewSessionName.setText(_translate("DialogNewSession", "New Session Name :"))
        self.labelTemplate.setText(_translate("DialogNewSession", "Template :"))

