# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/new_executable.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogNewExecutable(object):
    def setupUi(self, DialogNewExecutable):
        DialogNewExecutable.setObjectName("DialogNewExecutable")
        DialogNewExecutable.setWindowModality(QtCore.Qt.NonModal)
        DialogNewExecutable.resize(240, 338)
        DialogNewExecutable.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogNewExecutable)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelExecutable = QtWidgets.QLabel(DialogNewExecutable)
        self.labelExecutable.setObjectName("labelExecutable")
        self.verticalLayout.addWidget(self.labelExecutable)
        self.lineEdit = QtWidgets.QLineEdit(DialogNewExecutable)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxNsm = QtWidgets.QCheckBox(DialogNewExecutable)
        self.checkBoxNsm.setChecked(True)
        self.checkBoxNsm.setObjectName("checkBoxNsm")
        self.horizontalLayout.addWidget(self.checkBoxNsm)
        self.toolButtonAdvanced = QtWidgets.QToolButton(DialogNewExecutable)
        icon = QtGui.QIcon.fromTheme("arrow-down")
        self.toolButtonAdvanced.setIcon(icon)
        self.toolButtonAdvanced.setObjectName("toolButtonAdvanced")
        self.horizontalLayout.addWidget(self.toolButtonAdvanced)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBoxAdvanced = QtWidgets.QGroupBox(DialogNewExecutable)
        self.groupBoxAdvanced.setObjectName("groupBoxAdvanced")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxAdvanced)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditPrefix = QtWidgets.QLineEdit(self.groupBoxAdvanced)
        self.lineEditPrefix.setObjectName("lineEditPrefix")
        self.gridLayout.addWidget(self.lineEditPrefix, 2, 1, 1, 1)
        self.comboBoxPrefixMode = QtWidgets.QComboBox(self.groupBoxAdvanced)
        self.comboBoxPrefixMode.setObjectName("comboBoxPrefixMode")
        self.gridLayout.addWidget(self.comboBoxPrefixMode, 1, 1, 1, 1)
        self.labelPrefix = QtWidgets.QLabel(self.groupBoxAdvanced)
        self.labelPrefix.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPrefix.setObjectName("labelPrefix")
        self.gridLayout.addWidget(self.labelPrefix, 2, 0, 1, 1)
        self.labelClientId = QtWidgets.QLabel(self.groupBoxAdvanced)
        self.labelClientId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelClientId.setObjectName("labelClientId")
        self.gridLayout.addWidget(self.labelClientId, 3, 0, 1, 1)
        self.lineEditClientId = QtWidgets.QLineEdit(self.groupBoxAdvanced)
        self.lineEditClientId.setObjectName("lineEditClientId")
        self.gridLayout.addWidget(self.lineEditClientId, 3, 1, 1, 1)
        self.labelPrefixMode = QtWidgets.QLabel(self.groupBoxAdvanced)
        self.labelPrefixMode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPrefixMode.setObjectName("labelPrefixMode")
        self.gridLayout.addWidget(self.labelPrefixMode, 1, 0, 1, 1)
        self.checkBoxStartClient = QtWidgets.QCheckBox(self.groupBoxAdvanced)
        self.checkBoxStartClient.setChecked(True)
        self.checkBoxStartClient.setObjectName("checkBoxStartClient")
        self.gridLayout.addWidget(self.checkBoxStartClient, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBoxAdvanced)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogNewExecutable)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogNewExecutable)
        self.buttonBox.accepted.connect(DialogNewExecutable.accept)
        self.buttonBox.rejected.connect(DialogNewExecutable.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogNewExecutable)

    def retranslateUi(self, DialogNewExecutable):
        _translate = QtCore.QCoreApplication.translate
        DialogNewExecutable.setWindowTitle(_translate("DialogNewExecutable", "New Executable Client"))
        self.labelExecutable.setText(_translate("DialogNewExecutable", "Executable :"))
        self.checkBoxNsm.setToolTip(_translate("DialogNewExecutable", "<html><head/><body><p>If program is not compatible with the NSM API, </p><p>you should launch it in proxy to define a config file !</p></body></html>"))
        self.checkBoxNsm.setText(_translate("DialogNewExecutable", "NSM Protocol"))
        self.toolButtonAdvanced.setToolTip(_translate("DialogNewExecutable", "<html><head/><body><p>Show more options ...</p></body></html>"))
        self.toolButtonAdvanced.setText(_translate("DialogNewExecutable", "..."))
        self.groupBoxAdvanced.setTitle(_translate("DialogNewExecutable", "Advanced"))
        self.comboBoxPrefixMode.setToolTip(_translate("DialogNewExecutable", "<html><head/><body><p>The Prefix Mode determines the pattern of the client files.</p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Session Name (Default) :<br/>The client files names start with the session name.</li><li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Client Name :<br/>The client files names start with the client name given by the client itself<br/>(as in Non Session Manager).</li><li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Custom :<br/>The client files names start with the prefix written below.</li></ul></body></html>"))
        self.labelPrefix.setText(_translate("DialogNewExecutable", "Prefix :"))
        self.labelClientId.setText(_translate("DialogNewExecutable", "Client ID :"))
        self.lineEditClientId.setToolTip(_translate("DialogNewExecutable", "<html><head/><body><p>Use it If you want to add to session a file made outside from a session.</p><p>If you let this line empty, the client_id will be automaticely generated.</p></body></html>"))
        self.labelPrefixMode.setText(_translate("DialogNewExecutable", "Prefix Mode :"))
        self.checkBoxStartClient.setText(_translate("DialogNewExecutable", "Start the client"))

