# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/nsm_properties.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(416, 372)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Frame)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelClientName = QtWidgets.QLabel(self.groupBox)
        self.labelClientName.setObjectName("labelClientName")
        self.gridLayout_2.addWidget(self.labelClientName, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 1, 1, 1)
        self.labelCapabilities = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCapabilities.sizePolicy().hasHeightForWidth())
        self.labelCapabilities.setSizePolicy(sizePolicy)
        self.labelCapabilities.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelCapabilities.setObjectName("labelCapabilities")
        self.gridLayout_2.addWidget(self.labelCapabilities, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.labelCapabilitiesColon = QtWidgets.QLabel(self.groupBox)
        self.labelCapabilitiesColon.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelCapabilitiesColon.setObjectName("labelCapabilitiesColon")
        self.gridLayout_2.addWidget(self.labelCapabilitiesColon, 3, 1, 1, 1)
        self.labelCapabilitiesTitle = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCapabilitiesTitle.sizePolicy().hasHeightForWidth())
        self.labelCapabilitiesTitle.setSizePolicy(sizePolicy)
        self.labelCapabilitiesTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelCapabilitiesTitle.setObjectName("labelCapabilitiesTitle")
        self.gridLayout_2.addWidget(self.labelCapabilitiesTitle, 3, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolButtonIcon = FakeToolButton(self.groupBox)
        self.toolButtonIcon.setBaseSize(QtCore.QSize(48, 48))
        self.toolButtonIcon.setStyleSheet("QToolButton{border:none}")
        icon = QtGui.QIcon.fromTheme("application-pdf")
        self.toolButtonIcon.setIcon(icon)
        self.toolButtonIcon.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonIcon.setObjectName("toolButtonIcon")
        self.verticalLayout_4.addWidget(self.toolButtonIcon)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 2, 3, 2, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(Frame)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.labelExecutableWarning = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.labelExecutableWarning.setFont(font)
        self.labelExecutableWarning.setObjectName("labelExecutableWarning")
        self.verticalLayout_8.addWidget(self.labelExecutableWarning)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.lineEditExecutable = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditExecutable.setObjectName("lineEditExecutable")
        self.verticalLayout_8.addWidget(self.lineEditExecutable)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.groupBox_4 = QtWidgets.QGroupBox(Frame)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.lineEditArguments = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditArguments.setObjectName("lineEditArguments")
        self.verticalLayout_9.addWidget(self.lineEditArguments)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.groupBox_4)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.labelClientName.setText(_translate("Frame", "client_name"))
        self.label_3.setText(_translate("Frame", ":"))
        self.labelCapabilities.setText(_translate("Frame", "client_capabilities"))
        self.label_2.setText(_translate("Frame", "Name"))
        self.labelCapabilitiesColon.setText(_translate("Frame", ":"))
        self.labelCapabilitiesTitle.setText(_translate("Frame", "Capabilities"))
        self.toolButtonIcon.setText(_translate("Frame", "..."))
        self.labelExecutableWarning.setText(_translate("Frame", "<html><head/><body><p>Edit executable is strongly discouraged !<br/>It can be useful if you use many versions of a same software.<br/>Change it only if you are sure of what you are doing.</p></body></html>"))
        self.label_4.setText(_translate("Frame", "Executable :"))
        self.label_11.setText(_translate("Frame", "<html><head/><body><p>Arguments are supposed to not be supported by NSM protocol.<br/>In some cases it can works, but no warranty !</p></body></html>"))
        self.label_12.setText(_translate("Frame", "Arguments :"))

from surclassed_widgets import FakeToolButton
