  add_application_redesign[m
  applications_improve[m
  c++patchbay[m
  eye_for_gui[m
  eye_gui_button[m
  fedopipe[m
  manual[m
  master[m
  new_start_stop_icons[m
  nsm_file_format[m
  open_session_improve[m
  patchbay[m
  provide_logs[m
  proxyclose[m
  pulseaudio_many[m
* [32mrecent_sessions[m
  remove[m
  rm_launchall[m
  script_user_action_outside[m
  session_notes[m
  session_properties[m
  systray[m
  test_general_window[m
  test_hostname[m
  test_jack[m
  test_qt_tr[m
  the_patchbay[m
  waituser_dialog_left[m
