
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



ADD = '/ray/gui/trash/add'
CLEAR = '/ray/gui/trash/clear'
RAY_HACK_UPDATE = '/ray/gui/trash/ray_hack_update'
RAY_NET_UPDATE = '/ray/gui/trash/ray_net_update'
REMOVE = '/ray/gui/trash/remove'