
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.

from . import client
from . import control
from . import favorites
from . import gui
from . import monitor
from . import net_daemon
from . import patch_scenario
from . import patchbay
from . import server
from . import session
from . import trashed_client

