
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



AUTO_SNAPSHOT = '/ray/gui/session/auto_snapshot'
DUPLICATE_ONLY = '/ray/gui/session/duplicate_only'
IS_NSM = '/ray/gui/session/is_nsm'
NAME = '/ray/gui/session/name'
NOTES = '/ray/gui/session/notes'
NOTES_HIDDEN = '/ray/gui/session/notes_hidden'
NOTES_SHOWN = '/ray/gui/session/notes_shown'
RENAMEABLE = '/ray/gui/session/renameable'
SORT_CLIENTS = '/ray/gui/session/sort_clients'
ALTERNATIVE_GROUPS = '/ray/gui/session/alternative_groups'
' (arg types: ss*)'
