
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



REMOVE_DEFINITELY = '/ray/trashed_client/remove_definitely'
' (arg types: s)'

REMOVE_KEEP_FILES = '/ray/trashed_client/remove_keep_files'
' (arg types: s)'

RESTORE = '/ray/trashed_client/restore'
' (arg types: s)'
