
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



ADD_XRUN = '/ray/patchbay/monitor/add_xrun'
ANNOUNCE = '/ray/patchbay/monitor/announce'
BIG_PACKETS = '/ray/patchbay/monitor/big_packets'
BUFFER_SIZE = '/ray/patchbay/monitor/buffer_size'
CLIENT_NAME_AND_UUID = '/ray/patchbay/monitor/client_name_and_uuid'
CONNECTION_ADDED = '/ray/patchbay/monitor/connection_added'
CONNECTION_REMOVED = '/ray/patchbay/monitor/connection_removed'
DSP_LOAD = '/ray/patchbay/monitor/dsp_load'
METADATA_UPDATED = '/ray/patchbay/monitor/metadata_updated'
PORT_ADDED = '/ray/patchbay/monitor/port_added'
PORT_REMOVED = '/ray/patchbay/monitor/port_removed'
PORT_RENAMED = '/ray/patchbay/monitor/port_renamed'
SAMPLE_RATE = '/ray/patchbay/monitor/sample_rate'
SERVER_LOSE = '/ray/patchbay/monitor/server_lose'
SERVER_STARTED = '/ray/patchbay/monitor/server_started'
SERVER_STOPPED = '/ray/patchbay/monitor/server_stopped'
TRANSPORT_POSITION = '/ray/patchbay/monitor/transport_position'
UPDATE_GROUP_POSITION = '/ray/patchbay/monitor/update_group_position'
UPDATE_GROUP_PRETTY_NAME = '/ray/patchbay/monitor/update_group_pretty_name'
UPDATE_PORT_PRETTY_NAME = '/ray/patchbay/monitor/update_port_pretty_name'
UPDATE_PORTGROUP = '/ray/patchbay/monitor/update_portgroup'
PRETTY_NAMES_LOCKED = '/ray/patchbay/monitor/pretty_names_locked'
'1 if pretty names are locked by another patchbay daemon (arg types: i)'

VIEWS_CHANGED = '/ray/patchbay/monitor/views_changed'