
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



CLIENT_EVENT = '/nsm/client/monitor/client_event'
CLIENT_UPDATED = '/nsm/client/monitor/client_updated'