from server import *
from session import *

from Client import Client


def start():...
def start_new():...    
def start_new_hidden():...
def stop():...
def list_daemons() -> list[int]:...
def get_root() -> str:...
def get_port() -> int:...
def get_port_gui_free(wanted_session_root='') -> int | None:...
def get_pid() -> int:...
def get_session_path() -> str:...
def has_local_gui() -> bool:...
def has_gui() -> bool:...

def clients(started: bool | None =None,
            active: bool | None =None,
            auto_start: bool | None=None,
            no_save_level: bool | None =None) -> list[Client]:...
def trashed_clients() -> list[Client]:...

