from typing import overload

def abort_copy() -> bool:
    ...

def abort_parrallel_copy() -> bool:
    ...

def abort_snapshot() -> bool:
    ...

def ask_for_patchbay() -> bool:
    ...

def patchbay_daemon_ready() -> bool:
    ...

def change_root(arg_1: str) -> bool:
    ...

def clear_client_templates_database() -> bool:
    ...

def controller_announce() -> bool:
    ...

def controller_disannounce() -> bool:
    ...

def exotic_action() -> bool:
    ...

def get_session_preview() -> str:
    ...

def gui_announce() -> bool:
    ...

def gui_disannounce() -> bool:
    ...

def has_option() -> bool:
    ...

def hide_script_info() -> bool:
    ...

def list_factory_client_templates() -> list[str]:
    ...

def list_path() -> list[str]:
    ...

def list_session_templates() -> list[str]:
    ...

def list_sessions() -> list[str]:
    ...

def list_user_client_templates() -> list[str]:
    ...

def monitor_announce() -> bool:
    ...

def monitor_quit() -> bool:
    ...

def new_session() -> bool:
    ...

def open_file_manager_at() -> bool:
    ...

@overload
def open_session(arg_1: str) -> bool:
    ...

@overload
def open_session(arg_1: str, arg_2: int) -> bool:
    ...

@overload
def open_session(arg_1: str, arg_2: int, arg_3: str) -> bool:
    ...

def open_session_off() -> bool:
    ...

def quit() -> bool:
    ...

def remove_client_template() -> bool:
    ...

def rename_session() -> bool:
    ...

def save_session_template() -> bool:
    ...

def script_info() -> bool:
    ...

def script_user_action() -> bool:
    ...

def set_nsm_locked() -> bool:
    ...

def set_option() -> bool:
    ...

def set_options() -> bool:
    ...

def set_terminal_command() -> bool:
    ...

def export_custom_names() -> bool:
    ...

def import_pretty_names() -> bool:
    ...

def clear_pretty_names() -> bool:
    ...

def auto_export_custom_names(arg_1: int) -> bool:
    ...

def set_patch_keyword(arg_1: str) -> bool:
    ...
