
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.

from . import monitor

GUI_IS_HIDDEN = '/nsm/client/gui_is_hidden'
GUI_IS_SHOWN = '/nsm/client/gui_is_shown'
HIDE_OPTIONAL_GUI = '/nsm/client/hide_optional_gui'
IS_CLEAN = '/nsm/client/is_clean'
IS_DIRTY = '/nsm/client/is_dirty'
LABEL = '/nsm/client/label'
MESSAGE = '/nsm/client/message'
NETWORK_PROPERTIES = '/nsm/client/network_properties'
OPEN = '/nsm/client/open'
PROGRESS = '/nsm/client/progress'
SAVE = '/nsm/client/save'
SESSION_IS_LOADED = '/nsm/client/session_is_loaded'
SHOW_OPTIONAL_GUI = '/nsm/client/show_optional_gui'