
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.

from . import client
from . import client_template
from . import favorites
from . import listed_session
from . import patchbay
from . import preview
from . import server
from . import session
from . import trash

HIDE_SCRIPT_INFO = '/ray/gui/hide_script_info'
HIDE_SCRIPT_USER_ACTION = '/ray/gui/hide_script_user_action'
SCRIPT_INFO = '/ray/gui/script_info'
'Ask the GUI to show a dialog with arg as text. (arg types: s)'

SCRIPT_USER_ACTION = '/ray/gui/script_user_action'