
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.

from . import favorites
from . import server
from . import trash
from . import patchbay
from . import listed_session
from . import client
from . import preview
from . import session

CLIENT_TEMPLATE_RAY_HACK_UPDATE = '/ray/gui/client_template_ray_hack_update'
CLIENT_TEMPLATE_RAY_NET_UPDATE = '/ray/gui/client_template_ray_net_update'
CLIENT_TEMPLATE_UPDATE = '/ray/gui/client_template_update'
HIDE_SCRIPT_INFO = '/ray/gui/hide_script_info'
HIDE_SCRIPT_USER_ACTION = '/ray/gui/hide_script_user_action'
SCRIPT_INFO = '/ray/gui/script_info'
'Ask the GUI to show a dialog with arg as text. (arg types: s)'

SCRIPT_USER_ACTION = '/ray/gui/script_user_action'