
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



IS_STARTED = '/ray/gui/preview/client/is_started'
' (arg types: si)'

RAY_HACK_UPDATE = '/ray/gui/preview/client/ray_hack_update'
RAY_NET_UPDATE = '/ray/gui/preview/client/ray_net_update'
UPDATE = '/ray/gui/preview/client/update'