
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



ADDED = '/ray/gui/favorites/added'
' (arg types: ssis)'

REMOVED = '/ray/gui/favorites/removed'
' (arg types: si)'
