
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.

from . import ray
from . import nsm
from . import osc

ERROR = '/error'
MINOR_ERROR = '/minor_error'
REPLY = '/reply'