
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.

from . import monitor

ACTIVATE_DSP_LOAD = '/ray/patchbay/activate_dsp_load'
ACTIVATE_TRANSPORT = '/ray/patchbay/activate_transport'
ADD_GUI = '/ray/patchbay/add_gui'
CONNECT = '/ray/patchbay/connect'
' (arg types: ss)'

CONNECT_FAILED = '/ray/patchbay/connect_failed'
' (arg types: ss)'

DISCONNECT = '/ray/patchbay/disconnect'
' (arg types: ss)'

GROUP_CUSTOM_NAME = '/ray/patchbay/group_custom_name'
GUI_DISANNOUNCE = '/ray/patchbay/gui_disannounce'
PORT_CUSTOM_NAME = '/ray/patchbay/port_custom_name'
REFRESH = '/ray/patchbay/refresh'
SAVE_GROUP_CUSTOM_NAME = '/ray/patchbay/save_group_custom_name'
SAVE_PORT_CUSTOM_NAME = '/ray/patchbay/save_port_custom_name'
ENABLE_JACK_PRETTY_NAMING = '/ray/patchbay/enable_jack_pretty_naming'
EXPORT_ALL_CUSTOM_NAMES = '/ray/patchbay/export_all_custom_names'
IMPORT_ALL_PRETTY_NAMES = '/ray/patchbay/import_all_pretty_names'
CLEAR_ALL_PRETTY_NAMES = '/ray/patchbay/clear_all_pretty_names'
SET_BUFFER_SIZE = '/ray/patchbay/set_buffer_size'
TRANSPORT_PLAY = '/ray/patchbay/transport_play'
TRANSPORT_RELOCATE = '/ray/patchbay/transport_relocate'
TRANSPORT_STOP = '/ray/patchbay/transport_stop'