
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



ACTIVATE_DSP_LOAD = '/ray/patchbay/activate_dsp_load'
ACTIVATE_TRANSPORT = '/ray/patchbay/activate_transport'
ADD_GUI = '/ray/patchbay/add_gui'
CONNECT = '/ray/patchbay/connect'
DISCONNECT = '/ray/patchbay/disconnect'
GROUP_PRETTY_NAME = '/ray/patchbay/group_pretty_name'
GUI_DISANNOUNCE = '/ray/patchbay/gui_disannounce'
PORT_PRETTY_NAME = '/ray/patchbay/port_pretty_name'
REFRESH = '/ray/patchbay/refresh'
SAVE_GROUP_PRETTY_NAME = '/ray/patchbay/save_group_pretty_name'
SAVE_PORT_PRETTY_NAME = '/ray/patchbay/save_port_pretty_name'
ENABLE_JACK_PRETTY_NAMING = '/ray/patchbay/enable_jack_pretty_naming'
SET_BUFFER_SIZE = '/ray/patchbay/set_buffer_size'
TRANSPORT_PLAY = '/ray/patchbay/transport_play'
TRANSPORT_RELOCATE = '/ray/patchbay/transport_relocate'
TRANSPORT_STOP = '/ray/patchbay/transport_stop'
QUIT = '/ray/patchbay/quit'
'ask the patchbay daemon to quit'
