
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



SET_KEYWORD = '/ray/patch_scenario/set_keyword'
' (arg types: s)'
