
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



ADD = '/ray/favorites/add'
' (arg types: ssis)'

REMOVE = '/ray/favorites/remove'
' (arg types: si)'
