
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.

from . import client

CLEAR = '/ray/gui/preview/clear'
NOTES = '/ray/gui/preview/notes'
' (arg types: s)'

SESSION_SIZE = '/ray/gui/preview/session_size'
SNAPSHOT = '/ray/gui/preview/snapshot'
' (arg types: s)'

STATE = '/ray/gui/preview/state'
' (arg types: i)'
