
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



DIRTY = '/ray/gui/client/dirty'
GUI_VISIBLE = '/ray/gui/client/gui_visible'
HAS_OPTIONAL_GUI = '/ray/gui/client/has_optional_gui'
MESSAGE = '/ray/gui/client/message'
NEW = '/ray/gui/client/new'
PROGRESS = '/ray/gui/client/progress'
RAY_HACK_UPDATE = '/ray/gui/client/ray_hack_update'
RAY_NET_UPDATE = '/ray/gui/client/ray_net_update'
STATUS = '/ray/gui/client/status'
STILL_RUNNING = '/ray/gui/client/still_running'
SWITCH = '/ray/gui/client/switch'
UPDATE = '/ray/gui/client/update'