
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



RAY_HACK_UPDATE = '/ray/gui/client_template/ray_hack_update'
RAY_NET_UPDATE = '/ray/gui/client_template/ray_net_update'
UPDATE = '/ray/gui/client_template/update'