from PyQt5.QtGui import QPalette, QColor

def negate(color):
    return QColor(255 - color.red(), 255 - color.green(), 255 - color.blue())

class CarlaPalette(QPalette):
    def __init__(self, black=True):
        QPalette.__init__(self)
        
        if black:
            self.setBlack()
        else:
            self.setWhite()
        
    def setBlack(self):
        self.setColor(QPalette.Disabled, QPalette.Window, QColor(14, 14, 14))
        self.setColor(QPalette.Active,   QPalette.Window, QColor(17, 17, 17))
        self.setColor(QPalette.Inactive, QPalette.Window, QColor(17, 17, 17))
        self.setColor(QPalette.Disabled, QPalette.WindowText, QColor(83, 83, 83))
        self.setColor(QPalette.Active,   QPalette.WindowText, QColor(240, 240, 240))
        self.setColor(QPalette.Inactive, QPalette.WindowText, QColor(240, 240, 240))
        self.setColor(QPalette.Disabled, QPalette.Base, QColor(6, 6, 6))
        self.setColor(QPalette.Active,   QPalette.Base, QColor(7, 7, 7))
        self.setColor(QPalette.Inactive, QPalette.Base, QColor(7, 7, 7))
        self.setColor(QPalette.Disabled, QPalette.AlternateBase, QColor(12, 12, 12))
        self.setColor(QPalette.Active,   QPalette.AlternateBase, QColor(14, 14, 14))
        self.setColor(QPalette.Inactive, QPalette.AlternateBase, QColor(14, 14, 14))
        self.setColor(QPalette.Disabled, QPalette.ToolTipBase, QColor(4, 4, 4))
        self.setColor(QPalette.Active,   QPalette.ToolTipBase, QColor(4, 4, 4))
        self.setColor(QPalette.Inactive, QPalette.ToolTipBase, QColor(4, 4, 4))
        self.setColor(QPalette.Disabled, QPalette.ToolTipText, QColor(230, 230, 230))
        self.setColor(QPalette.Active,   QPalette.ToolTipText, QColor(230, 230, 230))
        self.setColor(QPalette.Inactive, QPalette.ToolTipText, QColor(230, 230, 230))
        self.setColor(QPalette.Disabled, QPalette.Text, QColor(74, 74, 74))
        self.setColor(QPalette.Active,   QPalette.Text, QColor(230, 230, 230))
        self.setColor(QPalette.Inactive, QPalette.Text, QColor(230, 230, 230))
        self.setColor(QPalette.Disabled, QPalette.Button, QColor(24, 24, 24))
        self.setColor(QPalette.Active,   QPalette.Button, QColor(28, 28, 28))
        self.setColor(QPalette.Inactive, QPalette.Button, QColor(28, 28, 28))
        self.setColor(QPalette.Disabled, QPalette.ButtonText, QColor(90, 90, 90))
        self.setColor(QPalette.Active,   QPalette.ButtonText, QColor(240, 240, 240))
        self.setColor(QPalette.Inactive, QPalette.ButtonText, QColor(240, 240, 240))
        self.setColor(QPalette.Disabled, QPalette.BrightText, QColor(255, 255, 255))
        self.setColor(QPalette.Active,   QPalette.BrightText, QColor(255, 255, 255))
        self.setColor(QPalette.Inactive, QPalette.BrightText, QColor(255, 255, 255))
        self.setColor(QPalette.Disabled, QPalette.Light, QColor(191, 191, 191))
        self.setColor(QPalette.Active,   QPalette.Light, QColor(191, 191, 191))
        self.setColor(QPalette.Inactive, QPalette.Light, QColor(191, 191, 191))
        self.setColor(QPalette.Disabled, QPalette.Midlight, QColor(155, 155, 155))
        self.setColor(QPalette.Active,   QPalette.Midlight, QColor(155, 155, 155))
        self.setColor(QPalette.Inactive, QPalette.Midlight, QColor(155, 155, 155))
        self.setColor(QPalette.Disabled, QPalette.Dark, QColor(129, 129, 129))
        self.setColor(QPalette.Active,   QPalette.Dark, QColor(129, 129, 129))
        self.setColor(QPalette.Inactive, QPalette.Dark, QColor(129, 129, 129))
        self.setColor(QPalette.Disabled, QPalette.Mid, QColor(94, 94, 94))
        self.setColor(QPalette.Active,   QPalette.Mid, QColor(94, 94, 94))
        self.setColor(QPalette.Inactive, QPalette.Mid, QColor(94, 94, 94))
        self.setColor(QPalette.Disabled, QPalette.Shadow, QColor(155, 155, 155))
        self.setColor(QPalette.Active,   QPalette.Shadow, QColor(155, 155, 155))
        self.setColor(QPalette.Inactive, QPalette.Shadow, QColor(155, 155, 155))
        self.setColor(QPalette.Disabled, QPalette.Highlight, QColor(14, 14, 14))
        self.setColor(QPalette.Active,   QPalette.Highlight, QColor(60, 60, 60))
        self.setColor(QPalette.Inactive, QPalette.Highlight, QColor(34, 34, 34))
        self.setColor(QPalette.Disabled, QPalette.HighlightedText, QColor(83, 83, 83))
        self.setColor(QPalette.Active,   QPalette.HighlightedText, QColor(255, 255, 255))
        self.setColor(QPalette.Inactive, QPalette.HighlightedText, QColor(240, 240, 240))
        self.setColor(QPalette.Disabled, QPalette.Link, QColor(34, 34, 74))
        self.setColor(QPalette.Active,   QPalette.Link, QColor(100, 100, 230))
        self.setColor(QPalette.Inactive, QPalette.Link, QColor(100, 100, 230))
        self.setColor(QPalette.Disabled, QPalette.LinkVisited, QColor(74, 34, 74))
        self.setColor(QPalette.Active,   QPalette.LinkVisited, QColor(230, 100, 230))
        self.setColor(QPalette.Inactive, QPalette.LinkVisited, QColor(230, 100, 230))
        
        self.setColor(QPalette.Disabled, QPalette.Button, QColor(24, 24, 24))
        self.setColor(QPalette.Active,   QPalette.Button, QColor(28, 28, 28))
        self.setColor(QPalette.Inactive, QPalette.Button, QColor(28, 28, 28))
        self.setColor(QPalette.Disabled, QPalette.ButtonText, QColor(90, 90, 90))
        self.setColor(QPalette.Active,   QPalette.ButtonText, QColor(240, 240, 240))
        self.setColor(QPalette.Inactive, QPalette.ButtonText, QColor(240, 240, 240))
        
    def setWhite(self):
        self.setColor(QPalette.Disabled, QPalette.Window, negate(QColor(14, 14, 14)))
        self.setColor(QPalette.Active,   QPalette.Window, negate(QColor(17, 17, 17)))
        self.setColor(QPalette.Inactive, QPalette.Window, negate(QColor(17, 17, 17)))
        self.setColor(QPalette.Disabled, QPalette.WindowText, negate(QColor(83, 83, 83)))
        self.setColor(QPalette.Active,   QPalette.WindowText, negate(QColor(240, 240, 240)))
        self.setColor(QPalette.Inactive, QPalette.WindowText, negate(QColor(240, 240, 240)))
        self.setColor(QPalette.Disabled, QPalette.Base, negate(QColor(6, 6, 6)))
        self.setColor(QPalette.Active,   QPalette.Base, negate(QColor(7, 7, 7)))
        self.setColor(QPalette.Inactive, QPalette.Base, negate(QColor(7, 7, 7)))
        self.setColor(QPalette.Disabled, QPalette.AlternateBase, negate(QColor(12, 12, 12)))
        self.setColor(QPalette.Active,   QPalette.AlternateBase, negate(QColor(14, 14, 14)))
        self.setColor(QPalette.Inactive, QPalette.AlternateBase, negate(QColor(14, 14, 14)))
        self.setColor(QPalette.Disabled, QPalette.ToolTipBase, negate(QColor(4, 4, 4)))
        self.setColor(QPalette.Active,   QPalette.ToolTipBase, negate(QColor(4, 4, 4)))
        self.setColor(QPalette.Inactive, QPalette.ToolTipBase, negate(QColor(4, 4, 4)))
        self.setColor(QPalette.Disabled, QPalette.ToolTipText, negate(QColor(230, 230, 230)))
        self.setColor(QPalette.Active,   QPalette.ToolTipText, negate(QColor(230, 230, 230)))
        self.setColor(QPalette.Inactive, QPalette.ToolTipText, negate(QColor(230, 230, 230)))
        self.setColor(QPalette.Disabled, QPalette.Text, negate(QColor(74, 74, 74)))
        self.setColor(QPalette.Active,   QPalette.Text, negate(QColor(230, 230, 230)))
        self.setColor(QPalette.Inactive, QPalette.Text, negate(QColor(230, 230, 230)))
        self.setColor(QPalette.Disabled, QPalette.Button, negate(QColor(24, 24, 24)))
        self.setColor(QPalette.Active,   QPalette.Button, negate(QColor(28, 28, 28)))
        self.setColor(QPalette.Inactive, QPalette.Button, negate(QColor(28, 28, 28)))
        self.setColor(QPalette.Disabled, QPalette.ButtonText, negate(QColor(90, 90, 90)))
        self.setColor(QPalette.Active,   QPalette.ButtonText, negate(QColor(240, 240, 240)))
        self.setColor(QPalette.Inactive, QPalette.ButtonText, negate(QColor(240, 240, 240)))
        self.setColor(QPalette.Disabled, QPalette.BrightText, negate(QColor(255, 255, 255)))
        self.setColor(QPalette.Active,   QPalette.BrightText, negate(QColor(255, 255, 255)))
        self.setColor(QPalette.Inactive, QPalette.BrightText, negate(QColor(255, 255, 255)))
        self.setColor(QPalette.Disabled, QPalette.Light, negate(QColor(191, 191, 191)))
        self.setColor(QPalette.Active,   QPalette.Light, negate(QColor(191, 191, 191)))
        self.setColor(QPalette.Inactive, QPalette.Light, negate(QColor(191, 191, 191)))
        self.setColor(QPalette.Disabled, QPalette.Midlight, negate(QColor(155, 155, 155)))
        self.setColor(QPalette.Active,   QPalette.Midlight, negate(QColor(155, 155, 155)))
        self.setColor(QPalette.Inactive, QPalette.Midlight, negate(QColor(155, 155, 155)))
        self.setColor(QPalette.Disabled, QPalette.Dark, negate(QColor(129, 129, 129)))
        self.setColor(QPalette.Active,   QPalette.Dark, negate(QColor(129, 129, 129)))
        self.setColor(QPalette.Inactive, QPalette.Dark, negate(QColor(129, 129, 129)))
        self.setColor(QPalette.Disabled, QPalette.Mid, negate(QColor(94, 94, 94)))
        self.setColor(QPalette.Active,   QPalette.Mid, negate(QColor(94, 94, 94)))
        self.setColor(QPalette.Inactive, QPalette.Mid, negate(QColor(94, 94, 94)))
        self.setColor(QPalette.Disabled, QPalette.Shadow, negate(QColor(155, 155, 155)))
        self.setColor(QPalette.Active,   QPalette.Shadow, negate(QColor(155, 155, 155)))
        self.setColor(QPalette.Inactive, QPalette.Shadow, negate(QColor(155, 155, 155)))
        self.setColor(QPalette.Disabled, QPalette.Highlight, negate(QColor(14, 14, 14)))
        self.setColor(QPalette.Active,   QPalette.Highlight, negate(QColor(60, 60, 60)))
        self.setColor(QPalette.Inactive, QPalette.Highlight, negate(QColor(34, 34, 34)))
        self.setColor(QPalette.Disabled, QPalette.HighlightedText, negate(QColor(83, 83, 83)))
        self.setColor(QPalette.Active,   QPalette.HighlightedText, negate(QColor(255, 255, 255)))
        self.setColor(QPalette.Inactive, QPalette.HighlightedText, negate(QColor(240, 240, 240)))
        self.setColor(QPalette.Disabled, QPalette.Link, negate(QColor(34, 34, 74)))
        self.setColor(QPalette.Active,   QPalette.Link, negate(QColor(100, 100, 230)))
        self.setColor(QPalette.Inactive, QPalette.Link, negate(QColor(100, 100, 230)))
        self.setColor(QPalette.Disabled, QPalette.LinkVisited, negate(QColor(74, 34, 74)))
        self.setColor(QPalette.Active,   QPalette.LinkVisited, negate(QColor(230, 100, 230)))
        self.setColor(QPalette.Inactive, QPalette.LinkVisited, negate(QColor(230, 100, 230)))
        
        self.setColor(QPalette.Disabled, QPalette.Button, negate(QColor(24, 24, 24)))
        self.setColor(QPalette.Active,   QPalette.Button, negate(QColor(28, 28, 28)))
        self.setColor(QPalette.Inactive, QPalette.Button, negate(QColor(28, 28, 28)))
        self.setColor(QPalette.Disabled, QPalette.ButtonText, negate(QColor(90, 90, 90)))
        self.setColor(QPalette.Active,   QPalette.ButtonText, negate(QColor(240, 240, 240)))
        self.setColor(QPalette.Inactive, QPalette.ButtonText, negate(QColor(240, 240, 240)))
