#!/usr/bin/python3 -u

from PyQt5.QtCore import QCoreApplication, QObject, QTimer, pyqtSignal
from PyQt5.QtXml import QDomDocument
import sys, signal, os

from shared import *
import jacklib
import nsm_client

connection_list = []
saved_connections = []
port_list = []

PORT_MODE_OUTPUT = 0
PORT_MODE_INPUT  = 1
PORT_MODE_NULL   = 2

PORT_TYPE_AUDIO = 0
PORT_TYPE_MIDI  = 1
PORT_TYPE_NULL  = 2


file_path = ""

def signalHandler(sig, frame):
    if sig in (signal.SIGINT, signal.SIGTERM):
        app.quit()

class JackPort(object):
    slots = ['name', 'mode', 'type']

def portExists(name, mode, port_type):
    for port in port_list:
        if port.name == name and port.mode == mode and port.type == port_type:
            return True
    return False

class Signaler(nsm_client.NSMSignaler):
    new_port_added = pyqtSignal()

def JackPortRegistrationCallback(portId, registerYesNo, arg=None):
    #print(portId, registerYesNo, arg)
    portPtr = jacklib.port_by_id(jack_client, portId)
    portFlags = jacklib.port_flags(portPtr)
    portName = str(jacklib.port_name(portPtr), encoding="utf-8")
    
    jack_port = JackPort()
    jack_port.name = portName
    
    if portFlags & jacklib.JackPortIsInput:
        jack_port.mode = PORT_MODE_INPUT
    elif portFlags & jacklib.JackPortIsOutput:
        jack_port.mode = PORT_MODE_OUTPUT
    else:
        jack_port.mode = PORT_MODE_NULL
        
    portTypeStr = str(jacklib.port_type(portPtr), encoding="utf-8")
    if portTypeStr == jacklib.JACK_DEFAULT_AUDIO_TYPE:
        jack_port.type = PORT_TYPE_AUDIO
    elif portTypeStr == jacklib.JACK_DEFAULT_MIDI_TYPE:
        jack_port.type = PORT_TYPE_MIDI
    else:
        jack_port.type = PORT_TYPE_NULL
            
    if registerYesNo:
        port_list.append(jack_port)
        signaler.new_port_added.emit()
    else:
        i=0
        for port in port_list:
            if port.name == jack_port.name and port.mode == jack_port.mode and port.type == jack_port.type:
                break
            i+=1
        
        if i >= len(port_list):
            return
        
        port_list.__delitem__(i)

def JackPortConnectCallback(port_id_A, port_id_B, connect_yesno, arg=None):
    port_ptr_A = jacklib.port_by_id(jack_client, port_id_A)
    port_ptr_B = jacklib.port_by_id(jack_client, port_id_B)
     
    port_str_A = str(jacklib.port_name(port_ptr_A), encoding="utf-8")
    port_str_B = str(jacklib.port_name(port_ptr_B), encoding="utf-8")
    
    if connect_yesno:
        connection_list.append((port_str_A, port_str_B))
    else:
        print('disco')
        for i in range(len(connection_list)):
            if connection_list[i][0] == port_str_A and connection_list[i][1] == port_str_B:
                connection_list.__delitem__(i)
                break

def makeMayConnections():
    output_ports = []
    input_ports  = []
    for jack_port in port_list:
        if jack_port.mode == PORT_MODE_OUTPUT:
            output_ports.append(jack_port.name)
        elif jack_port.mode == PORT_MODE_INPUT:
            input_ports.append(jack_port.name)
    
    for connection in saved_connections:
        print('how_savved')
        if connection[0] in output_ports and connection[1] in input_ports:
            print('making connection')
            jacklib.connect(jack_client, connection[0], connection[1])

def c_char_p_p_to_list(c_char_p_p):
    i = 0
    retList = []

    if not c_char_p_p:
        return retList

    while True:
        new_char_p = c_char_p_p[i]
        if new_char_p:
            retList.append(str(new_char_p, encoding="utf-8"))
            i += 1
        else:
            break

    jacklib.free(c_char_p_p)
    return retList


#jacklib.connect(jack_client, "system:capture_1", "system:playback_5")

def openFile(project_path, session_name, full_client_id):
    #connection_list.clear()
    
    global file_path
    file_path = "%s.xml" % project_path
    
    if not os.path.isfile(file_path):
        port_list.clear()
        
    else:
        file = open(file_path, 'r')
        xml = QDomDocument()
        xml.setContent(file.read())
        
        content = xml.documentElement()
        
        if content.tagName() != "RAY-PATCHER":
            file.close()
            NSMServer.sendToDeamon('/reply', '/nsm/client/open', 'Ready')
            return
        
        cte = content.toElement()
        node = cte.firstChild()
        
        while not node.isNull():
            el = node.toElement()
            if el.tagName() != "connection":
                continue
            
            port_from = el.attribute('from')
            port_to   = el.attribute('to')
            
            saved_connections.append((port_from, port_to))
            
            node = node.nextSibling()
        
        makeMayConnections()
        
    NSMServer.sendToDeamon('/reply', '/nsm/client/open', 'Ready')

def saveFile():
    if not file_path:
        return
    
    #tmp_saved_conn = []
    
    for connection in connection_list:
        if not connection in saved_connections:
            saved_connections.append(connection)
    
    delete_list = []
    
    for i in range(len(saved_connections)):
        if portExists(saved_connections[i][0], PORT_MODE_OUTPUT, PORT_TYPE_AUDIO) and portExists(saved_connections[i][1], PORT_MODE_INPUT, PORT_TYPE_AUDIO):
            if not saved_connections[i] in connection_list:
                delete_list.append(i)
                
    delete_list.reverse()
    for i in delete_list:
        saved_connections.__delitem__(i)
    
    
    
    #for connection in saved_connections:
        #if connection in tmp_saved_conn:
            #continue
        
        #if connection in connection_list or not (portExists(connection[0], PORT_MODE_OUTPUT, PORT_TYPE_AUDIO) and portExists(connection[1], PORT_MODE_INPUT, PORT_TYPE_AUDIO)):
            #tmp_saved_conn.append(connection)
    
    #saved_connections.clear()
    #for connection in tmp_saved_conn:
        #saved_connections.append(connection)
    
    file = open(file_path, 'w')
    xml = QDomDocument()
    p = xml.createElement('RAY-PATCHER')
    
    for con in saved_connections:
        ct = xml.createElement('connection')
        ct.setAttribute('from', con[0])
        ct.setAttribute('to'  , con[1])
        p.appendChild(ct)
        
    xml.appendChild(p)
    
    file.write(xml.toString())
    file.close()
    
    NSMServer.sendToDeamon('/reply', '/nsm/client/save', 'Saved')
    

if __name__ == '__main__':
    jack_client = jacklib.client_open("ray-patcher", jacklib.JackNoStartServer | jacklib.JackSessionID, None)
    jacklib.set_port_registration_callback(jack_client, JackPortRegistrationCallback, None)
    jacklib.set_port_connect_callback(jack_client, JackPortConnectCallback, None)
    jacklib.activate(jack_client)
    
    NSM_URL = os.getenv('NSM_URL')
    if not NSM_URL:
        print('Could not register as NSM client.', file=sys.stderr)
        sys.exit()
    
    deamon_address = getLibloAddress(NSM_URL)
    
    signaler = Signaler()
    signaler.new_port_added.connect(makeMayConnections)
    signaler.server_sends_open.connect(openFile)
    signaler.server_sends_save.connect(saveFile)
    
    NSMServer = nsm_client.NSMThread('ray-patcher', signaler, deamon_address, False)
    NSMServer.start()
    NSMServer.announce('Ray Patcher', '', 'ray-patcher')
    
    #connect signals
    signal.signal(signal.SIGINT , signalHandler)
    signal.signal(signal.SIGTERM, signalHandler)
    
    
    
    portNameList = c_char_p_p_to_list(jacklib.get_ports(jack_client, "", "", 0))
    
    for portName in portNameList:
        jack_port = JackPort()
        jack_port.name = portName
        
        portPtr = jacklib.port_by_name(jack_client, portName)
        portFlags = jacklib.port_flags(portPtr)
        
        if portFlags & jacklib.JackPortIsInput:
            jack_port.mode = PORT_MODE_INPUT
        elif portFlags & jacklib.JackPortIsOutput:
            jack_port.mode = PORT_MODE_OUTPUT
        else:
            jack_port.mode = PORT_MODE_NULL
        
        portTypeStr = str(jacklib.port_type(portPtr), encoding="utf-8")
        if portTypeStr == jacklib.JACK_DEFAULT_AUDIO_TYPE:
            jack_port.type = PORT_TYPE_AUDIO
        elif portTypeStr == jacklib.JACK_DEFAULT_MIDI_TYPE:
            jack_port.type = PORT_TYPE_MIDI
        else:
            jack_port.type = PORT_TYPE_NULL
        
        port_list.append(jack_port)
        
        
        # Only make connections from an output port
        if jacklib.port_flags(portPtr) & jacklib.JackPortIsInput:
            continue

        portConnectionNames = c_char_p_p_to_list(jacklib.port_get_all_connections(jack_client, portPtr))

        for portConName in portConnectionNames:
            connection_list.append((portName, portConName))
            #self.canvas_connectPortsByName(portName, portConName)
    
    #for jack_port in port_list:
        #print(jack_port.name, jack_port.mode, jack_port.type)
    print(connection_list)
    app = QCoreApplication(sys.argv)
    
    #needed for signals SIGINT, SIGTERM
    timer = QTimer()
    timer.start(200)
    timer.timeout.connect(lambda: None)
    
    makeMayConnections()
    app.exec()
    
    jacklib.deactivate(jack_client)
    jacklib.client_close(jack_client)
