#!/usr/bin/python3 -u

import os, sys, string, random, time, subprocess, signal, unicodedata
from liblo import ServerThread, Address, make_method, Message
from PyQt5.QtCore import QCoreApplication, pyqtSignal, qDebug, QObject, QTimer, QProcess, QSettings, QLocale, QTranslator, QFile
from PyQt5.QtWidgets import QApplication, QDialog, QFileDialog, QMessageBox, QMainWindow
from PyQt5.QtXml import QDomDocument

from shared import *
import nsm_client
import ui_proxy_gui, ui_proxy_copy

ERR_OK                =  0
ERR_NO_PROXY_FILE     = -1
ERR_NOT_ENOUGHT_LINES = -2
ERR_NO_EXECUTABLE     = -3
ERR_WRONG_ARGUMENTS   = -4
ERR_WRONG_SAVE_SIGNAL = -5
ERR_WRONG_STOP_SIGNAL = -6



save_signals = {'None'   : None, 
                'SIGUSR1': signal.SIGUSR1, 
                'SIGUSR2': signal.SIGUSR2,
                'SIGINT' : signal.SIGINT }

stop_signals = {'SIGTERM': signal.SIGTERM,
                'SIGINT' : signal.SIGINT,
                'SIGHUP' : signal.SIGHUP}

def signalHandler(sig, frame):
    if sig in (signal.SIGINT, signal.SIGTERM):
        proxy.stopProcess()
        sys.exit()
        
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return u"".join([c for c in nfkd_form if not unicodedata.combining(c)]).lower()    

def ifDebug(string):
    if debug:
        print(string, file=sys.stderr)

class ProxyCopyDialog(QDialog):
    def __init__(self):
        QDialog.__init__(self)
        self.ui = ui_proxy_copy.Ui_Dialog()
        self.ui.setupUi(self)
        
        self.rename_file = False
        self.ui.pushButtonCopyRename.clicked.connect(self.setRenameFile)
        
    def setRenameFile(self):
        self.rename_file = True
        self.accept()
    
    def setFile(self, path):
        self.ui.labelFileNotInFolder.setText(_translate('Dialog', '%s is not in proxy directory') % ('<strong>' + os.path.basename(path) + '</strong>'))

class ProxyDialog(QMainWindow):
    def __init__(self, executable=''):
        QMainWindow.__init__(self)
        self.ui = ui_proxy_gui.Ui_MainWindow()
        self.ui.setupUi(self)
        
        
        self.config_file = ''
        self.args_edited  = False
        self.fields_allow_start = False
        self.process_is_running = False
        
        self.ui.comboSaveSig.addItems(['None', 'SIGUSR1', 'SIGUSR2', 'SIGINT'])
        self.ui.comboStopSig.addItems(['SIGTERM', 'SIGINT', 'SIGHUP'])
        self.ui.toolButtonBrowse.clicked.connect(self.browseFile)
        
        self.ui.lineEditExecutable.textEdited.connect(self.lineEditExecutableEdited)
        self.ui.lineEditArguments.textChanged.connect(self.lineEditArgumentsChanged)
        self.ui.lineEditConfigFile.textChanged.connect(self.lineEditConfigFileChanged)
        
        self.ui.comboSaveSig.currentTextChanged.connect(self.allowSaveTest)
        self.ui.toolButtonTestSave.clicked.connect(self.testSave)
        self.ui.toolButtonTestSave.setEnabled(False)
        
        self.ui.pushButtonStart.clicked.connect(self.startProcess)
        self.ui.pushButtonStop.clicked.connect(self.stopProcess)
        self.ui.pushButtonStop.setEnabled(False)
        
        self.ui.lineEditExecutable.setText(executable)
        self.lineEditExecutableEdited(executable)
        
        self.ui.labelError.setText('')
        
        proxy.process.started.connect(self.proxyStarted)
        proxy.process.finished.connect(self.proxyFinished)
        proxy.process.errorOccurred.connect(self.proxyErrorInProcess)
    
    def checkAllowStart(self):
        self.fields_allow_start = True
        if not self.ui.lineEditExecutable.text():
            self.fields_allow_start = False
        
        if shellLineToArgs(self.ui.lineEditArguments.text()) == None:
            self.fields_allow_start = False

        self.ui.pushButtonStart.setEnabled(bool(not self.process_is_running and self.fields_allow_start))
        
    def updateValuesFromProxyFile(self):
        proxy_file = proxy.proxy_file
        
        self.ui.lineEditExecutable.setText(proxy_file.executable)
        self.ui.lineEditConfigFile.setText(proxy_file.config_file)
        self.ui.lineEditArguments.setText(proxy_file.arguments_line)
        
        for sig_str in save_signals:
            if save_signals[sig_str] == proxy_file.save_signal:
                self.ui.comboSaveSig.setCurrentText(sig_str)
                break
        
        for sig_str in stop_signals:
            if stop_signals[sig_str] == proxy_file.stop_signal:
                self.ui.comboStopSig.setCurrentText(sig_str)
                break
        
        self.checkAllowStart()
        
    def firstLaunch(self, executable, config_file, arguments_line, save_signal, stop_signal):
        self.ui.lineEditExecutable.setText(executable)
        self.ui.lineEditConfigFile.setText(config_file)
        self.ui.lineEditArguments.setText(arguments_line)
        self.yet_connected = True
        self.show()
    
    def browseFile(self):
        config_file, ok = QFileDialog.getOpenFileName(self, _translate('Dialog', 'Select File to use as CONFIG_FILE'))
        if not ok:
            return
        
        if not config_file.startswith(os.getcwd() + '/'):
            qfile = QFile(config_file)
            if qfile.size() < 20971520:   #if file < 20Mb
                copy_dialog = ProxyCopyDialog()
                copy_dialog.setFile(config_file)
                copy_dialog.exec()
                
                if copy_dialog.result():
                    if copy_dialog.rename_file:
                        base, pt, extension = os.path.basename(config_file).rpartition('.')
                        
                        config_file = "%s.%s" % (proxy.session_name, extension)
                        if not base:
                            config_file = proxy.session_name
                    else:
                        config_file = os.path.basename(config_file)
                        
                    qfile.copy(config_file)
            
        self.config_file = os.path.relpath(config_file)
        self.ui.lineEditConfigFile.setText(self.config_file)
    
    def lineEditExecutableEdited(self, text):
        self.checkAllowStart()
    
    def lineEditArgumentsChanged(self, text):
        self.checkAllowStart()
        if shellLineToArgs(text) != None:
            self.ui.lineEditArguments.setStyleSheet('')
        else:
            self.ui.lineEditArguments.setStyleSheet('QLineEdit{background: red}')
            self.ui.pushButtonStart.setEnabled(False)
    
    def lineEditConfigFileChanged(self, text):
        if text and not self.ui.lineEditArguments.text():
            self.ui.lineEditArguments.setText('"$CONFIG_FILE"')
        elif not text and self.ui.lineEditArguments.text() == '"$CONFIG_FILE"':
            self.ui.lineEditArguments.setText('')
    
    def allowSaveTest(self, text=None):
        if text == None:
            text = self.ui.comboSaveSig.currentText()
            
        self.ui.toolButtonTestSave.setEnabled(bool(self.process_is_running and text != 'None'))
    
    def testSave(self):
        save_signal = save_signals[self.ui.comboSaveSig.currentText()]
        proxy.saveProcess(save_signal)
    
    def saveProxyFile(self):
        executable     = self.ui.lineEditExecutable.text()
        config_file    = self.ui.lineEditConfigFile.text()
        arguments_line = self.ui.lineEditArguments.text()
        save_signal    = save_signals[self.ui.comboSaveSig.currentText()]
        stop_signal    = stop_signals[self.ui.comboStopSig.currentText()]
        
        proxy.proxy_file.saveFile(executable, config_file, arguments_line, save_signal, stop_signal)
    
    def startProcess(self):
        self.saveProxyFile()
        
        if proxy.proxy_file.is_launchable:
            proxy.startProcess()
        
    def stopProcess(self):
        proxy.stopProcess(stop_signals[self.ui.comboStopSig.currentText()])
        
    def proxyStarted(self):
        self.process_is_running = True
        self.ui.pushButtonStart.setEnabled(False)
        self.ui.pushButtonStop.setEnabled(True)
        self.allowSaveTest()
        self.ui.labelError.setText('')
        
    def processTerminateShortly(self, duration):
        self.ui.labelError.setText('Process terminate in %f ms')
        
    def proxyFinished(self):
        self.process_is_running = False
        self.ui.pushButtonStart.setEnabled(self.fields_allow_start)
        self.ui.pushButtonStop.setEnabled(False)
        self.allowSaveTest()
        self.ui.labelError.setText('')
    
    def proxyErrorInProcess(self):
        self.ui.labelError.setText(_translate('Dialog', 'Executable failed to launch ! It\'s maybe not present on system.'))
        if not self.isVisible():
            self.show()
    
    def closeEvent(self, event):
        server.sendToDeamon('/nsm/client/gui_is_hidden')
        settings.setValue('ProxyGui%s/geometry' % proxy.full_client_id, self.saveGeometry())
        settings.setValue('ProxyGui%s/WindowState'% proxy.full_client_id, self.saveState())
        settings.sync()
        
        if self.fields_allow_start:
            self.saveProxyFile()
        
        QMainWindow.closeEvent(self, event)
        
        #Quit if process is not running yet
        if not proxy.process.state() == QProcess.Running:
            sys.exit(0)
        
    def showEvent(self, event):
        server.sendToDeamon('/nsm/client/gui_is_shown')
        
        if settings.value('ProxyGui%s/geometry' % proxy.full_client_id):
            self.restoreGeometry(settings.value('ProxyGui%s/geometry' % proxy.full_client_id))
        if settings.value('ProxyGui%s/WindowState' % proxy.full_client_id):
            self.restoreState(settings.value('ProxyGui%s/WindowState' % proxy.full_client_id))
        
        self.updateValuesFromProxyFile()
        
        QMainWindow.showEvent(self, event)
##########################

class Proxy(QObject):
    def __init__(self, executable=''):
        QObject.__init__(self)
        self.process = QProcess()
        self.process.setProcessChannelMode(QProcess.ForwardedChannels)
        self.process.finished.connect(self.processFinished)
        
        self.proxy_file     = None
        self.project_path   = None
        self.session_name   = None
        self.full_client_id = None
        
        self.executable     = executable
        self.arguments      = []
        self.arguments_line = ''
        self.config_file    = None
        self.save_signal    = None
        self.stop_signal    = signal.SIGTERM
        self.label          = None
        
        self.timer_open = QTimer()
        self.timer_open.setSingleShot(True)
        self.timer_open.setInterval(500)
        self.timer_open.timeout.connect(self.timerOpenFinished)
        
        self.is_finishable = False
        self.timer_close = QTimer()
        self.timer_close.setSingleShot(True)
        self.timer_close.setInterval(2500)
        self.timer_close.timeout.connect(self.timerCloseFinished)
        self.timer_close.start()
        self.process_start_time = time.time()
        
        signaler.server_sends_open.connect(self.initialize)
        signaler.server_sends_save.connect(self.saveProcess)
        signaler.show_optional_gui.connect(self.showOptionalGui)
        signaler.hide_optional_gui.connect(self.hideOptionalGui)
    
    def isRunning(self):
        return bool(self.process.state() == QProcess.Running)
    
    def processFinished(self, exit_code):
        if self.is_finishable:
            if not proxy_dialog.isVisible():
                sys.exit(0)
        else:
            duration = time.time() - self.process_start_time
            proxy_dialog.processTerminateShortly(duration)
            #proxy_dialog.show()
            
    def initialize(self, project_path, session_name, full_client_id):
        self.project_path   = project_path
        self.session_name   = session_name
        self.full_client_id = full_client_id
        
        server.sendToDeamon('/nsm/client/gui_is_hidden')
        
        if not os.path.exists(project_path):
            os.mkdir(project_path)
        
        os.chdir(project_path)
        
        proxy_dialog.setWindowTitle(self.full_client_id)
        
        self.proxy_file = ProxyFile(project_path, self.executable)
        self.proxy_file.readFile()
        
        proxy_dialog.updateValuesFromProxyFile()
        
        if not self.proxy_file.is_launchable:
            server.sendToDeamon('/reply', '/nsm/client/open', 'Ready')
            proxy_dialog.show()
            return
        
        self.startProcess()
        
    def startProcess(self):
        os.environ['NSM_CLIENT_ID']    = self.full_client_id
        os.environ['NSM_SESSION_NAME'] = self.session_name
        
        #enable environment vars in config_file
        config_file = os.path.expandvars(self.proxy_file.config_file)
        os.environ['CONFIG_FILE'] = config_file
        
        #Useful for launching with specifics arguments clients NSM compatible
        os.unsetenv('NSM_URL')
        
        arguments_line = os.path.expandvars(self.proxy_file.arguments_line)
        arguments = shellLineToArgs(arguments_line)
        
        self.process.start(self.proxy_file.executable, arguments)
        self.timer_open.start()
    
    def saveProcess(self, save_signal=None):
        if not save_signal:
            save_signal = self.proxy_file.save_signal
        
        if self.isRunning() and save_signal:
            os.kill(self.process.processId(), save_signal)
            
        server.sendToDeamon('/reply', '/nsm/client/save', 'Saved.')
    
    def stopProcess(self, signal=signal.SIGTERM):
        if not self.isRunning():
            return
        
        os.kill(self.process.processId(), signal)
    
    def timerOpenFinished(self):
        server.sendToDeamon('/reply', '/nsm/client/open', 'Ready.')
        if self.isRunning() and proxy_dialog.isVisible():
            proxy_dialog.close()
    
    def timerCloseFinished(self):
        self.is_finishable = True    
    
    def stop(self):
        if self.process.state:
            self.process.terminate()
    
    def showOptionalGui(self):
        proxy_dialog.show()
    
    def hideOptionalGui(self):
        proxy_dialog.close()

class ProxyFile(object):
    def __init__(self, project_path, executable=''):
        self.file = None
        self.path = "%s/ray-proxy.xml" % project_path
        
        self.executable  = executable
        self.arguments_line = ''
        self.config_file = ''
        self.args_line   = ''
        self.save_signal = None
        self.stop_signal = signal.SIGTERM
        
        self.is_launchable = False
        
    def readFile(self):
        self.is_launchable = False
        try:
            file = open(self.path, 'r')
        except:
            return
        
        xml = QDomDocument()
        xml.setContent(file.read())

        content = xml.documentElement()
        
        if content.tagName() != "RAY-PROXY":
            file.close()
            return
        
        cte = content.toElement()
        self.executable     = cte.attribute('executable')
        self.config_file    = cte.attribute('config_file')
        self.arguments_line = cte.attribute('arguments')
        save_signal         = cte.attribute('save_signal')
        stop_signal         = cte.attribute('stop_signal')
        
        
        file.close()
        
        if save_signal.isdigit() and int(save_signal) in save_signals.values():
            self.save_signal = int(save_signal)
        
        if stop_signal.isdigit() and int(stop_signal) in stop_signals.values():
            self.stop_signal = int(stop_signal)
            
        if not self.executable:
            return
        
        arguments = shellLineToArgs(self.arguments_line)
        if arguments == None:
            return
        
        self.is_launchable = True
    
    def saveFile(self, executable, config_file, arguments_line, save_signal, stop_signal):
        try:
            file = open(self.path, 'w')
        except:
            return
        
        if not save_signal:
            save_signal = 0
            
        xml = QDomDocument()
        p = xml.createElement('RAY-PROXY')
        p.setAttribute('VERSION', VERSION)
        p.setAttribute('executable', executable)
        p.setAttribute('arguments', arguments_line)
        p.setAttribute('config_file', config_file)
        p.setAttribute('save_signal', str(int(save_signal)))
        p.setAttribute('stop_signal', str(int(save_signal)))
        
        xml.appendChild(p)
        
        contents = "<?xml version='1.0' encoding='UTF-8'?>\n"
        contents+= "<!DOCTYPE RAY-PROXY>\n"
        contents+= xml.toString()
        
        file.write(contents)
        file.close()
        
        self.readFile()
        
if __name__ == '__main__':
    NSM_URL = os.getenv('NSM_URL')
    if not NSM_URL:
        print('Could not register as NSM client.', file=sys.stderr)
        sys.exit()
    
    deamon_address = getLibloAddress(NSM_URL)
    
    parser = argparse.ArgumentParser()
    parser.add_argument('--executable', default='')
    parser.add_argument('--debug','-d',  action='store_true', help='see all OSC messages')
    parser.add_argument('-v', '--version', action='version', version=VERSION)
    parsed_args = parser.parse_args()
    
    debug      = parsed_args.debug
    executable = parsed_args.executable
    
    signal.signal(signal.SIGINT,  signalHandler)
    signal.signal(signal.SIGTERM, signalHandler)
    
    app = QApplication(sys.argv)
    app.setApplicationName("RaySession")
    #app.setApplicationVersion(VERSION)
    app.setOrganizationName("RaySession")
    app.setQuitOnLastWindowClosed(False)
    settings = QSettings()
    
    ## Translation process
    locale = QLocale.system().name()
    appTranslator = QTranslator()
    if appTranslator.load("%s/locale/raysession_%s" % (os.path.dirname(os.path.dirname(sys.argv[0])), locale)):
        app.installTranslator(appTranslator)
    _translate = app.translate
    
    timer = QTimer()
    timer.setInterval(200)
    timer.timeout.connect(lambda: None)
    timer.start()
    
    
    signaler = nsm_client.NSMSignaler()
        
    proxy = Proxy(executable)    
    proxy_dialog = ProxyDialog()
    
    server = nsm_client.NSMThread('ray-proxy', signaler, deamon_address, debug)
    server.start()
    server.announce('Ray Proxy', ':optional-gui:', 'ray-proxy')
    
    
    app.exec()
    
    settings.sync()
    server.stop()
    
    del server
    del proxy
    del app
    
