#!/usr/bin/python3 -u


import os, sys, time, signal
from liblo import ServerThread, Address, make_method, Message
from PyQt5.QtCore import QCoreApplication, pyqtSignal, QObject, QTimer, QProcess, QSettings, QLocale, QTranslator, QFile
#from PyQt5.QtWidgets import QApplication, QDialog, QFileDialog, QMessageBox, QMainWindow
from PyQt5.QtXml import QDomDocument

from shared import *
import nsm_client

def signalHandler(sig, frame):
    if sig in (signal.SIGINT, signal.SIGTERM):
        #sys.exit()
        general_object.leave()
        app.quit()

class SlThread(nsm_client.NSMThread):
    def __init__(self, name, signaler, daemon_address, debug):
        nsm_client.NSMThread.__init__(self, name, signaler, daemon_address, debug)
        
    @make_method('/re-load', None)
    def reLoad(self, path, args):
        print('mamamlaoad')
        print(args)
        
    @make_method('/re-save', None)
    def resave(self, path, args):
        print('mamamsave')
        print(args)
        
    

class GeneralObject(QObject):
    def __init__(self):
        QObject.__init__(self)
        self.sl_process  = QProcess()
        self.sl_process.finished.connect(self.slProcessFinished)
        
        self.sl_port = getFreeOscPort(9951)
        self.sl_url = Address(self.sl_port)
        
        
        self.sl_process.start('sooperlooper', ['-p', str(self.sl_port)])
        
        self.gui_process = QProcess()
        self.gui_process.started.connect(self.guiProcessStarted)
        self.gui_process.finished.connect(self.guiProcessFinished)
        
        self.project_path   = ''
        self.session_name   = ''
        self.full_client_id = ''
        
        signaler.server_sends_open.connect(self.initialize)
        signaler.server_sends_save.connect(self.saveSlSession)
        signaler.show_optional_gui.connect(self.showOptionalGui)
        signaler.hide_optional_gui.connect(self.hideOptionalGui)
        
        self.leaving = False
    
    def leave(self):
        self.leaving = True
        
        if self.gui_process.state():
            self.gui_process.terminate()
        else:
            if self.sl_process.state():
                self.sl_process.terminate()
            else:
                app.quit()
    
    def slProcessFinished(self, exit_code):
        app.quit()
    
    def guiProcessStarted(self):
        server.sendToDaemon('/nsm/client/gui_is_shown')
    
    def guiProcessFinished(self, exit_code):
        if self.leaving:
            if self.sl_process.state():
                self.sl_process.terminate()
            else:
                app.quit()
                
        server.sendToDaemon('/nsm/client/gui_is_hidden')
    
    def initialize(self, project_path, session_name, full_client_id):
        self.project_path   = project_path
        self.session_name   = session_name
        self.full_client_id = full_client_id
        
        print('eieiiei')
        
        server.send(self.sl_url, '/load_session', "%s.slsess" % self.project_path, server.url, '/re-load')
        
        server.sendToDaemon('/reply', '/nsm/client/open', 'Ready')
        
    def saveSlSession(self):
         server.send(self.sl_url, '/save_session', "%s.slsess" % self.project_path, server.url, '/re-save')
         
         server.sendToDaemon('/reply', '/nsm/client/save', 'Saved')
         #todo save audio
         
    def showOptionalGui(self):
        if not self.gui_process.state():
            self.gui_process.start('slgui', ['-P', str(self.sl_port)])
        
        
    def hideOptionalGui(self):
        if self.gui_process.state():
            self.gui_process.terminate()
        
        
if __name__ == '__main__':
    NSM_URL = os.getenv('NSM_URL')
    if not NSM_URL:
        print('Could not register as NSM client.', file=sys.stderr)
        sys.exit()
        
    daemon_address = getLibloAddress(NSM_URL)
    #daemon_address = getLibloAddress('osc.udp://houston-MS-75922:16187/')

    
    
    signal.signal(signal.SIGINT,  signalHandler)
    signal.signal(signal.SIGTERM, signalHandler)
    
    app = QCoreApplication(sys.argv)
    app.setApplicationName("SooperLooperNSM")
    #app.setApplicationVersion(VERSION)
    app.setOrganizationName("SooperLooperNSM")
    
    timer = QTimer()
    timer.setInterval(200)
    timer.timeout.connect(lambda: None)
    timer.start()
    
    signaler = nsm_client.NSMSignaler()
    
    server = nsm_client.NSMThread('sooperlooper_nsm', signaler, daemon_address, False)
    
    general_object = GeneralObject()
    
    server.start()
    server.announce('SooperLooper', ':optional-gui:switch:', 'sooperlooper_nsm')
    
    app.exec()
    
    server.stop()
    
    del server
    del app
