# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/patchbay/filter_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(740, 41)
        Frame.setStyleSheet("QFrame{border:none}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolButtonCloseFilterBar = QtWidgets.QToolButton(Frame)
        self.toolButtonCloseFilterBar.setStyleSheet("QToolButton{border:none}")
        icon = QtGui.QIcon.fromTheme("window-close")
        self.toolButtonCloseFilterBar.setIcon(icon)
        self.toolButtonCloseFilterBar.setObjectName("toolButtonCloseFilterBar")
        self.verticalLayout_2.addWidget(self.toolButtonCloseFilterBar)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lineEditGroupFilter = FilterBar(Frame)
        self.lineEditGroupFilter.setClearButtonEnabled(True)
        self.lineEditGroupFilter.setObjectName("lineEditGroupFilter")
        self.horizontalLayout.addWidget(self.lineEditGroupFilter)
        self.toolButtonUp = QtWidgets.QToolButton(Frame)
        self.toolButtonUp.setStyleSheet("")
        icon = QtGui.QIcon.fromTheme("arrow-up")
        self.toolButtonUp.setIcon(icon)
        self.toolButtonUp.setObjectName("toolButtonUp")
        self.horizontalLayout.addWidget(self.toolButtonUp)
        self.toolButtonDown = QtWidgets.QToolButton(Frame)
        self.toolButtonDown.setStyleSheet("")
        icon = QtGui.QIcon.fromTheme("arrow-down")
        self.toolButtonDown.setIcon(icon)
        self.toolButtonDown.setObjectName("toolButtonDown")
        self.horizontalLayout.addWidget(self.toolButtonDown)
        spacerItem2 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.labelBoxes = QtWidgets.QLabel(Frame)
        self.labelBoxes.setMinimumSize(QtCore.QSize(60, 0))
        self.labelBoxes.setText("")
        self.labelBoxes.setObjectName("labelBoxes")
        self.horizontalLayout.addWidget(self.labelBoxes)
        self.checkBoxAudioFilter = QtWidgets.QCheckBox(Frame)
        self.checkBoxAudioFilter.setChecked(True)
        self.checkBoxAudioFilter.setObjectName("checkBoxAudioFilter")
        self.horizontalLayout.addWidget(self.checkBoxAudioFilter)
        self.checkBoxMidiFilter = QtWidgets.QCheckBox(Frame)
        self.checkBoxMidiFilter.setChecked(True)
        self.checkBoxMidiFilter.setObjectName("checkBoxMidiFilter")
        self.horizontalLayout.addWidget(self.checkBoxMidiFilter)
        spacerItem3 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBoxOpacity = QtWidgets.QSpinBox(Frame)
        self.spinBoxOpacity.setMinimum(2)
        self.spinBoxOpacity.setMaximum(70)
        self.spinBoxOpacity.setProperty("value", 17)
        self.spinBoxOpacity.setObjectName("spinBoxOpacity")
        self.horizontalLayout.addWidget(self.spinBoxOpacity)
        spacerItem4 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.toolButtonCloseFilterBar.setToolTip(_translate("Frame", "Hide filter bar"))
        self.toolButtonCloseFilterBar.setText(_translate("Frame", "..."))
        self.lineEditGroupFilter.setPlaceholderText(_translate("Frame", "Find a box..."))
        self.toolButtonUp.setText(_translate("Frame", "..."))
        self.toolButtonDown.setText(_translate("Frame", "..."))
        self.checkBoxAudioFilter.setText(_translate("Frame", "Audio"))
        self.checkBoxMidiFilter.setText(_translate("Frame", "Midi"))
        self.label.setToolTip(_translate("Frame", "adjust the opacity of boxes not matching with the filter"))
        self.label.setText(_translate("Frame", "Opacity :"))
        self.spinBoxOpacity.setToolTip(_translate("Frame", "adjust the opacity of boxes not matching with the filter"))
        self.spinBoxOpacity.setSuffix(_translate("Frame", "%"))
from ..surclassed_widgets import FilterBar
